# Scene lists for bold-and-easy 40-page books (STYLE.md).
# Each entry is the SUBJECT only — prompts always wrap with the style prefix and NO TEXT.

STYLE_PREFIX = (
    "Square coloring-book line art, bold and easy cozy style like Quiet Places. "
    "Medium-weight clean closed black outlines on pure white background. "
    "No solid black fills, no shading, no gray, no hatching. "
    "Absolutely NO letters, NO words, NO numbers, NO readable text or signage. "
    "Fill the entire square frame with one cohesive illustrated scene. "
    "Cute hand-drawn look, large simple shapes, easy to color. "
)

THEMES = {
    "stained-glass-40": {
        "prefix": "sg",
        "out_prefix": "sg2",
        "title": "Stained Glass",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Window panels, roses, animals, and geometric glass patterns in big bold outlines.",
        "keywords": [
            "stained glass coloring book",
            "bold and easy coloring",
            "window patterns coloring",
            "stress relief coloring",
            "simple stained glass designs",
            "adult coloring bold lines",
            "glass pattern coloring book",
        ],
        "query": "stained glass bold easy coloring book",
        "cover_rgb": ((230, 220, 245), (70, 40, 110)),
        "cover_accent": (255, 200, 120),
        "back_label": "Color the light",
        "gradient": ((210, 195, 240), (80, 45, 120)),
        "scenes": [
            "rose window with petal segments and center circle",
            "tall cathedral arch window with simple geometric panes",
            "butterfly made of stained glass wing panels",
            "sunflower stained glass panel with radiating petals",
            "owl portrait in stained glass segments",
            "lotus flower stained glass medallion",
            "tree of life stained glass with simple branches and leaves",
            "heart medallion of leaded glass shapes",
            "peacock with stained glass fan tail segments",
            "dragonfly stained glass with wing panes",
            "moon and stars stained glass night panel",
            "fish swimming stained glass oval window",
            "tulip bouquet in stained glass vase panel",
            "geometric diamond lattice stained glass",
            "circular mandala-like stained glass without tiny detail",
            "birdhouse and bird stained glass scene",
            "sailboat on water stained glass panel",
            "mountain and sun stained glass landscape window",
            "cat silhouette filled with stained glass patches",
            "mushroom cottage stained glass fairy panel",
            "honeycomb hex stained glass pattern (large cells only)",
            "seashell stained glass spiral panel",
            "hot air balloon stained glass sky panel",
            "lantern with stained glass sides glowing shape only no fill",
            "garden gate with stained glass flowers above",
            "unicorn head stained glass portrait simple",
            "whale stained glass ocean panel",
            "pumpkin and leaves autumn stained glass",
            "snowflake large stained glass crystal",
            "coffee cup and steam stained glass cozy panel",
            "bicycle with flower basket stained glass",
            "lighthouse and waves stained glass",
            "fox stained glass forest portrait",
            "pineapple stained glass tropical panel",
            "umbrella and raindrops stained glass",
            "teapot and cup stained glass still life",
            "camper van stained glass travel panel",
            "sunflower field row as stained glass strips",
            "angel fish reef stained glass",
            "simple house facade stained glass window collage",
        ],
    },
    "cars-40": {
        "prefix": "car",
        "out_prefix": "car2",
        "title": "Cars",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Cute cars, trucks, and road scenes in big bold outlines for easy coloring.",
        "keywords": [
            "cars coloring book",
            "bold and easy cars",
            "truck coloring pages",
            "vehicle coloring book kids",
            "simple car designs",
            "stress relief coloring cars",
            "automobile coloring book",
        ],
        "query": "cars trucks bold easy coloring book",
        "cover_rgb": ((230, 235, 245), (30, 60, 120)),
        "cover_accent": (255, 180, 70),
        "back_label": "Hit the road",
        "gradient": ((180, 210, 245), (30, 70, 130)),
        "scenes": [
            "cute round compact car parked on a quiet street with trees",
            "classic convertible with flowers in the back seat",
            "school bus on a country road with hills",
            "fire truck with ladder and cute details no text",
            "ice cream truck with cone icons only no words",
            "pickup truck with pumpkins in the bed autumn",
            "vintage VW-style beetle with flowers",
            "police car cute rounded style no badges text",
            "taxi cab rounded cozy style no lettering",
            "camper van at a campsite with tent and trees",
            "sports car on a winding coastal road",
            "monster truck jumping over dirt mounds",
            "racecar on a simple track with checkered flags as shapes no text",
            "delivery van with heart logo only",
            "tractor on a farm with barn and fields",
            "jeep on a mountain trail with pines",
            "family station wagon packed for vacation with suitcases",
            "hot rod with big wheels and flame shapes on body as outlines",
            "electric car charging at a cute home charger",
            "limousine with balloons floating nearby",
            "tow truck helping a small broken car",
            "garbage truck with smiling face style cute",
            "cement mixer truck on a construction lot",
            "food truck park scene with picnic tables no menus text",
            "car wash scene with soap bubbles and brushes",
            "drive-in movie car facing a blank screen shape",
            "parking garage ramp with two cute cars",
            "road trip car and trailer overlooking a canyon",
            "snowy car with ski rack and pine trees",
            "beach buggy near dunes and surfboard",
            "taxi line outside a train station building exterior",
            "car ferry boarding with ocean waves",
            "mechanic garage with car on a lift cozy",
            "parade car covered in flowers float style",
            "go-kart track with two karts",
            "ambulance cute rounded emergency vehicle no text",
            "mail truck at suburban mailboxes no text",
            "car under a starry night camping overlook",
            "classic muscle car at a diner exterior no neon text",
            "two cars racing side by side on a desert highway",
        ],
    },
    "planes-40": {
        "prefix": "pln",
        "out_prefix": "pln2",
        "title": "Planes",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Airplanes, airports, and sky adventures in big bold easy outlines.",
        "keywords": [
            "planes coloring book",
            "airplane coloring pages",
            "bold and easy aviation",
            "airport coloring book",
            "flying machines coloring",
            "kids plane coloring",
            "stress relief planes coloring",
        ],
        "query": "airplanes bold easy coloring book",
        "cover_rgb": ((220, 235, 250), (40, 90, 150)),
        "cover_accent": (255, 200, 90),
        "back_label": "Up in the clouds",
        "gradient": ((190, 220, 245), (40, 90, 150)),
        "scenes": [
            "propeller plane flying over rolling hills and clouds",
            "passenger jet taking off from runway with control tower",
            "biplane looping above a meadow",
            "seaplane landing on a calm lake with mountains",
            "hot air balloon festival multiple balloons no text",
            "helicopter over a city skyline simple buildings",
            "glider soaring above cliffs by the ocean",
            "cargo plane loading at an airport hangar",
            "paper airplane flock over a park (large simple)",
            "private jet on a tarmac with mountains behind",
            "crop duster over farm fields and barn",
            "space shuttle style plane on a runway (simple)",
            "airplane window view of wing and clouds from inside outline",
            "airport terminal exterior with planes parked",
            "vintage triplane in a museum hangar",
            "flight of three jets in formation in clear sky",
            "plane flying over tropical islands and ocean",
            "ski plane landing on snowy runway with pines",
            "blimp floating over a fairground ferris wheel",
            "drone style small aircraft above a garden (simple cute)",
            "airplane pulling a blank banner (empty white rectangle no letters)",
            "kids toy plane on a bedroom shelf with clouds mural",
            "hangar doors open revealing a shiny plane",
            "plane flying through a rainbow over countryside",
            "night flight plane among stars and moon",
            "airplane over the grand canyon style cliffs",
            "floatplane docked at a wooden pier village",
            "pilot waving from open cockpit biplane cute no text",
            "runway lights and plane landing at dusk clouds",
            "airplane and airport luggage cart cute scene",
            "plane flying past a lighthouse coast",
            "stunt plane with smoke trails as outline swirls",
            "airplane over autumn forest canopy",
            "jet over desert dunes and cactus",
            "plane crossing above a suspension bridge city",
            "airplane cabin cozy seats aisle view simple no screens text",
            "control tower close-up with plane ascending",
            "plane flying beside migrating birds silhouette",
            "amphibious plane near waterfall jungle lake",
            "vintage travel poster style plane and globe as outlines no text",
        ],
    },
    "buildings-40": {
        "prefix": "bld",
        "out_prefix": "bld2",
        "title": "Buildings",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Cozy houses, shops, castles, and city scenes in big bold outlines.",
        "keywords": [
            "buildings coloring book",
            "houses coloring pages",
            "bold and easy architecture",
            "city coloring book",
            "cottage coloring",
            "castle coloring book easy",
            "cozy buildings coloring",
        ],
        "query": "buildings houses bold easy coloring book",
        "cover_rgb": ((235, 228, 220), (90, 70, 55)),
        "cover_accent": (255, 190, 120),
        "back_label": "Color the skyline",
        "gradient": ((230, 220, 210), (90, 70, 55)),
        "scenes": [
            "cozy cottage with flower boxes and stone path",
            "tall city skyscraper street scene with a few buildings",
            "fairytale castle with turrets and flags as blank shapes",
            "bakery storefront with cakes in window no text signs",
            "lighthouse on rocky shore at sunset clouds",
            "treehouse connected between two big trees",
            "barn and silo on a farm with fence",
            "japanese-style pagoda in a garden with lanterns",
            "library building with wide steps and columns no lettering",
            "fire station with garage doors and truck peeking",
            "beach house on stilts with palm trees",
            "mountain chalet with snow and pine trees",
            "windmill beside tulip fields",
            "train station platform with clock face no numbers readable blur as blank circle",
            "greenhouse glass house full of plants",
            "covered bridge over a creek in autumn",
            "downtown row of shop fronts awnings blank signs with hearts only",
            "museum building with grand staircase",
            "observatory dome on a hill under stars",
            "water tower and small town houses",
            "apartment balcony garden with hanging plants",
            "schoolhouse with playground swings no text",
            "harbor warehouse and fishing boats",
            "igloo village with northern lights swirls",
            "desert adobe pueblo style homes",
            "victorian house with wraparound porch",
            "modern glass house in a forest clearing",
            "clock tower square with fountain no readable clock numbers use blank face",
            "stadium exterior simple bold arches",
            "temple steps with statues simple garden",
            "factory with smokestacks stylized cute clouds",
            "motel courtyard poolside lounge chairs no neon text",
            "cabin in the woods with smoke from chimney",
            "bridge and gatehouse medieval town",
            "skyscraper rooftop garden with city view",
            "boathouse on a lake with canoe",
            "post office building cute with mailbox no text",
            "art gallery exterior with sculptures outside",
            "hospital building friendly rounded architecture no signs text",
            "spaceport terminal futuristic simple building and rocket",
        ],
    },
    "food-40": {
        "prefix": "food",
        "out_prefix": "food2",
        "title": "Food",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Cute meals, desserts, and picnic spreads in big bold easy outlines.",
        "keywords": [
            "food coloring book",
            "dessert coloring pages",
            "bold and easy food",
            "picnic coloring book",
            "cute food coloring",
            "snack coloring pages",
            "stress relief food coloring",
        ],
        "query": "food desserts bold easy coloring book",
        "cover_rgb": ((255, 235, 220), (160, 70, 50)),
        "cover_accent": (255, 210, 100),
        "back_label": "Dig in and color",
        "gradient": ((255, 230, 210), (170, 80, 55)),
        "scenes": [
            "stack of pancakes with butter and berries on a plate",
            "pizza with fun toppings on a wooden board",
            "ice cream sundae with cherry and whipped cream",
            "sushi platter with chopsticks and wasabi shapes",
            "burger and fries basket picnic style",
            "taco trio with lime and salsa bowls",
            "donut box open with assorted iced donuts no text",
            "fruit bowl overflowing with apples bananas grapes",
            "birthday cake with candles and sprinkles no writing on cake",
            "ramen bowl with egg chopsticks and steam",
            "picnic blanket spread with sandwiches and lemonade pitcher",
            "waffle with strawberries and syrup drizzle outlines",
            "hot cocoa mug with marshmallows and cookies",
            "avocado toast and soft boiled egg breakfast plate",
            "popcorn bucket and movie snacks cozy (blank bucket no text)",
            "cheese board with grapes crackers and honey jar",
            "smoothie bowls with kiwi blueberry toppings",
            "bbq grill with corn and veggies outdoors",
            "cupcake tower display stand",
            "spaghetti and meatballs with garlic bread",
            "croissant and coffee cup cafe table still life",
            "watermelon slice picnic with ants cute",
            "cookie jar overflowing with cookies",
            "breakfast burrito and salsa scene",
            "dim sum steamer baskets open",
            "pineapple upside down cake on a cake stand",
            "nachos platter with cheese and jalapeños",
            "tea time tray with scones and jam jars",
            "fish and chips newspaper wrap as blank paper texture no text",
            "salad bowl with veggies and dressing drizzle",
            "macaron tower pastel pastry shop window",
            "corn dogs and fair food booth no signage text",
            "oatmeal bowl with banana and cinnamon sticks",
            "grilled cheese and tomato soup cozy",
            "churros and chocolate dipping cup",
            "poke bowl with mango and avocado",
            "pumpkin pie slice thanksgiving table",
            "cotton candy and caramel apple carnival snacks",
            "veggie garden harvest basket overflow",
            "chocolate fountain with fruit skewers party table",
        ],
    },
    "mountains-40": {
        "prefix": "mtn",
        "out_prefix": "mtn2",
        "title": "Mountains",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Peaks, trails, lakes, and alpine cabins in big bold easy outlines.",
        "keywords": [
            "mountains coloring book",
            "nature landscape coloring",
            "bold and easy mountains",
            "hiking coloring pages",
            "alpine scenery coloring",
            "stress relief nature coloring",
            "peak landscape coloring book",
        ],
        "query": "mountains landscape bold easy coloring book",
        "cover_rgb": ((220, 235, 240), (50, 80, 100)),
        "cover_accent": (255, 200, 120),
        "back_label": "Reach the summit",
        "gradient": ((200, 225, 235), (50, 80, 105)),
        "scenes": [
            "snowy mountain peaks with pine forest and rising sun",
            "alpine lake reflecting mountains and a canoe",
            "hiking trail switchbacks with backpacker silhouette cute",
            "mountain cabin with chimney smoke and snow",
            "waterfall cascading from cliff into a pool",
            "mountain goats on a rocky ridge",
            "hot air balloon over mountain valleys",
            "ski chalet and ski lift chairs simple",
            "desert mountains with cactus and mesa",
            "volcano with gentle smoke puff and tropical plants",
            "mountain tunnel train emerging from rock",
            "campfire under mountain stars and tent",
            "rope bridge between two mountain cliffs",
            "eagle soaring over jagged peaks",
            "spring mountain meadow with wildflowers and peaks",
            "autumn aspen grove below rocky mountains",
            "mountain village with chalets and church steeple blank",
            "glacier tongue and icy blue cave entrance outlines",
            "mountain bike trail through pine woods to vista",
            "sunrise alpenglow on three pointed peaks",
            "mountain river rapids with rocks and pines",
            "lookout tower on a summit with binocular viewer",
            "mountain goats and marmot near wildflowers",
            "foggy mountain ridge with silhouettes of trees",
            "mountain pass road with hairpin turns and car",
            "cliffside monastery or temple simple bold",
            "mountain lake pier with Adirondack chairs",
            "avalanche barrier snow fences and peaks",
            "mountain wildflower alpine garden close scene with peaks behind",
            "cable car gondola over snowy slopes",
            "mountain storm clouds dramatic but simple outlines",
            "twin peaks with a rainbow between them",
            "mountain observatory under night sky",
            "hiker resting on a summit rock with map as blank rectangle",
            "mountain waterfall mill cabin scene",
            "rocky desert canyon mountains layered",
            "mountain zoo or reserve with deer in meadow peaks behind",
            "snowshoe trail through winter pines to peak view",
            "mountain vineyard terraces on hillsides",
            "full moon rising behind a single iconic peak",
        ],
    },
}
