# Trend-niche 40-page books. Same STYLE.md prefix as theme_scenes.THEMES.
# Interiors: full-frame bold-and-easy scenes. Never letters, numbers, Latin,
# verses, captions, recipes, lore sidebars, hatching, or grayscale.

TREND_THEMES = {
    "mushrooms-40": {
        "prefix": "msh",
        "out_prefix": "msh",
        "title": "Mushrooms",
        "subtitle": "40 Bold & Easy Designs for Cozy Coloring",
        "one_liner": "Toadstools, foraging baskets, and woodland mushroom cottages in big bold outlines.",
        "keywords": [
            "bold and easy mushrooms",
            "mushroom coloring book",
            "cozy woodland coloring",
            "toadstool coloring pages",
            "simple mushroom designs",
            "stress relief coloring seniors",
            "cottagecore mushroom coloring",
        ],
        "query": "bold and easy mushrooms coloring book",
        "cover_rgb": ((245, 228, 200), (120, 70, 45)),
        "cover_accent": (255, 190, 110),
        "back_label": "Forage and color",
        "gradient": ((236, 210, 170), (128, 72, 42)),
        "scenes": [
            "one large spotted toadstool in a mossy clearing with two round trees",
            "round mushroom cottage with a door and two windows on a grassy hill",
            "wicker basket of round mushrooms on a cottage doorstep",
            "cute snail beside one giant mushroom cap",
            "three chunky mushrooms on a knoll under a simple sun",
            "ladybug on a broad leaf next to one mushroom",
            "teacup on a stump beside a small mushroom cluster",
            "hedgehog sleeping under a mushroom umbrella",
            "red-cap mushroom with white dots in the rain with puddles",
            "five large mushrooms in a meadow ring",
            "foraging basket with mushrooms and ferns, cottage behind",
            "fox sitting under a wide mushroom canopy",
            "three round mushroom houses with glowing window shapes no text",
            "kitchen still life of mushrooms on a board with herbs no labels",
            "woodland picnic with round mushroom pies",
            "owl on a mushroom at night with a huge moon",
            "mouse family under a mushroom with acorn cups",
            "greenhouse full of potted mushrooms no signs",
            "large honeycomb morel beside a creek",
            "shelf mushrooms on a log by a stream",
            "leaf-hatted sprite sitting on a giant cap",
            "rain boots and a mushroom basket by a garden gate",
            "stone path through giant mushroom trees",
            "two squirrels sharing a mushroom",
            "market stall of round mushrooms with blank canopy no lettering",
            "moonlit mushroom meadow with round firefly dots",
            "glass globe terrarium with mushrooms and moss",
            "cottage window box of mushrooms and flowers",
            "hedgehog carrying a mushroom through fallen leaves",
            "mushroom tea party with an acorn teapot",
            "snowy stump with winter mushrooms and a pine",
            "cave of huge friendly mushroom formations",
            "frog on a lily pad looking at shoreline mushrooms",
            "mushroom stair-caps up a tree to a round door",
            "two friends walking with mushroom umbrellas",
            "big plate mushrooms on a trunk beside a creek",
            "mushroom wreath on a cottage door",
            "campfire with mushrooms on sticks and a kettle",
            "rows of giant mushrooms receding to rolling hills",
            "sunrise over a field of friendly giant mushrooms",
        ],
    },
    "botanicals-40": {
        "prefix": "btn",
        "out_prefix": "btn",
        "title": "Botanicals",
        "subtitle": "40 Bold & Easy Floral Designs to Color",
        "one_liner": "Succulents, tropical leaves, wreaths, and cozy bloom portraits in big bold outlines.",
        "keywords": [
            "botanical coloring book",
            "bold and easy florals",
            "succulent coloring pages",
            "flower coloring book adults",
            "wreath coloring book",
            "simple botanical designs",
            "monstera coloring book",
        ],
        "query": "botanical florals bold easy coloring book",
        "cover_rgb": ((250, 244, 232), (70, 110, 75)),
        "cover_accent": (255, 190, 130),
        "back_label": "Bloom and color",
        "gradient": ((245, 236, 214), (62, 108, 72)),
        "scenes": [
            "one sunflower in a simple clay pot on a windowsill",
            "single succulent in a round pot on a wooden table",
            "one hibiscus bloom with two big leaves",
            "tulip in a bottle vase on a blank table",
            "daisy bouquet in a round jug",
            "cactus in a square pot with two round spines clusters",
            "lavender bunch in a tin pot no labels",
            "rose in a bud vase beside a teacup",
            "monstera leaf in a simple standing pot",
            "bird of paradise flower in a tall pot",
            "pressed-flower tray of large blooms on a table no latin text",
            "succulent cluster in geometric pots on a shelf",
            "tropical patio with monstera, hibiscus, and a hammock",
            "wildflower meadow path with a cottage in the distance",
            "single-stem peony portrait with a garden behind",
            "spring cherry and daffodil garden bench",
            "summer sunflower field with a straw hat on a fence",
            "autumn chrysanthemum porch with pumpkins",
            "winter holly and amaryllis on a mantel",
            "herb garden with rosemary sage lavender no recipes",
            "circular floral wreath of roses and leaves on a door",
            "garland of greenery over a cottage mantel",
            "hanging plant swing with trailing vines",
            "greenhouse aisle with large potted tropicals",
            "windowsill row of succulents and a watering can",
            "lily pond edge with blooming water lilies",
            "magnolia branch over a garden path",
            "poppy field with a bicycle and basket of blooms",
            "orchid on a mossy branch in a bright room",
            "wild rose climbing a garden arch",
            "sunflower and bee as large friendly shapes",
            "terracotta potting bench with soil and sprouts",
            "flower cart with round blooms blank signs with a heart only",
            "peony and fern still life on a round table",
            "cactus desert garden with three chunky pots",
            "hibiscus hedge around a small fountain",
            "dried flower bundle hanging in a kitchen window",
            "garden gate overflowing with climbing blooms",
            "night garden with moonflowers and a lantern",
            "huge botanical bouquet filling a cottage parlor",
        ],
    },
    "celestial-40": {
        "prefix": "cel",
        "out_prefix": "cel",
        "title": "Celestial Mandalas",
        "subtitle": "40 Bold & Easy Moon and Bloom Wreaths",
        "one_liner": "Moon gardens, floral wreaths, and cozy radial night scenes in big bold outlines.",
        "keywords": [
            "celestial mandala coloring",
            "moon coloring book",
            "floral wreath coloring",
            "bold and easy mandala",
            "night garden coloring",
            "owl moon coloring pages",
            "simple radial floral coloring",
        ],
        "query": "celestial moon mandala bold easy coloring book",
        "cover_rgb": ((40, 40, 80), (20, 20, 50)),
        "cover_accent": (255, 210, 120),
        "back_label": "Color the night",
        "gradient": ((48, 52, 110), (18, 18, 48)),
        "scenes": [
            "new-moon night garden with one round dark moon and large flowers",
            "waxing crescent over a simple hill and three stars as dots",
            "full moon rising behind a round floral wreath",
            "waning moon over a quiet pond with lily pads",
            "sunflower arranged in a big circular bloom wreath",
            "rose vine circle around a sleeping cat",
            "butterfly in the center of a flower ring",
            "owl portrait inside a leafy circular wreath",
            "wolf sitting in a moonlit flower circle",
            "simple star-and-moon wreath on a cottage door",
            "crescent moon garden with climbing roses",
            "full-moon lake with a round dock and wreath of reeds",
            "owl in a radial pine-bough wreath at night",
            "wolf under a huge moon with a ring of wildflowers",
            "butterfly garden arranged in a circular path",
            "rose mandala as a round climbing trellis filled with blooms",
            "vine-wrapped moon gate in a garden wall",
            "night-blooming wreath around a lantern",
            "circular herb spiral garden seen from a cozy path",
            "starry wreath of cosmos flowers on a fence",
            "moon phases as four large moons over one rolling landscape no numbers",
            "cat sleeping in a radial daisy circle",
            "swan on a round pond framed by a willow wreath",
            "moth and moon inside a ring of night flowers",
            "sun and moon facing on a floral horizon wreath",
            "peacock tail as large simple fans in a circle of blooms",
            "lotus pond in a perfectly round garden basin",
            "circular stone labyrinth as large path coils in a meadow",
            "wreath of grapes and leaves on a kitchen door",
            "snow wreath of pine and berries on a winter door",
            "autumn leaf wreath around a smiling pumpkin",
            "sea-shell circular arrangement on a beach blanket",
            "bird nest centered in a blossom wreath",
            "hedgehog curled in a ring of mushrooms",
            "tea set arranged on a round doily of drawn flowers",
            "candle in the middle of a floral ring still life",
            "window looking onto a circular moon garden",
            "bridge over a round pond with wreath-like lily pads",
            "cottage seen through a huge blooming moon gate",
            "midnight meadow with a giant floral moon wreath overhead",
        ],
    },
    "cottagecore-40": {
        "prefix": "cot",
        "out_prefix": "cot",
        "title": "Cottagecore",
        "subtitle": "40 Bold & Easy Cozy Country Scenes",
        "one_liner": "Cottages, jam kitchens, tea tables, and garden gates in big bold outlines.",
        "keywords": [
            "cottagecore coloring book",
            "cozy cottage coloring",
            "bold and easy country scenes",
            "rustic kitchen coloring",
            "tea party coloring pages",
            "garden cottage coloring",
            "cozy aesthetic coloring book",
        ],
        "query": "cottagecore cozy cottage bold easy coloring book",
        "cover_rgb": ((236, 214, 186), (120, 72, 48)),
        "cover_accent": (210, 140, 80),
        "back_label": "Come in and color",
        "gradient": ((230, 200, 165), (118, 70, 46)),
        "scenes": [
            "small stone cottage with a smoking chimney and climbing roses",
            "loaf of bread rising in a round pan on a farm table",
            "three jam jars and a copper pot on a shelf",
            "teapot, scone, and wildflower vase on a table",
            "chicken coop and a simple garden gate",
            "picnic blanket with a basket in a meadow",
            "armchair, blanket, and stacked blank books by a window",
            "wicker foraging basket and an apron on a peg",
            "fox looking in a cottage window at night",
            "rabbit at a garden gate with carrots",
            "cottage exterior with ivy, chimney smoke, and a stone path",
            "rustic kitchen with bread, jam jars, and copper pots",
            "tea service still life with teapot scones and a flower jug",
            "hens in a coop beside a vegetable patch",
            "wildflower picnic with a checkered cloth of large squares",
            "cozy reading nook with armchair candle and blank books",
            "hedgehog and rabbit sharing the windowsill",
            "foraging apron and mushroom basket on a bench",
            "washing line of quilts behind a cottage",
            "well with a bucket in a herb garden",
            "jam-making table with berries and a copper pan",
            "cat asleep on a windowsill pie cooling nearby",
            "stone bridge to a thatched cottage",
            "wheelbarrow of pumpkins by a barn door",
            "greenhouse lean-to full of seedlings",
            "knitting basket beside a hearth with a kettle",
            "duck pond beside a cottage garden",
            "bee skeps and a wildflower border",
            "porch swing with cushions and a teacup",
            "inside the cottage: table set for two with flowers",
            "orchard ladder and a basket of round fruit",
            "rainy cottage with glowing windows and boots by the door",
            "sunrise over rolling fields and one cottage",
            "moonlit cottage garden with a lantern",
            "wood stove with a soup pot and hanging herbs no labels",
            "sleeping loft window with a quilt and a cat",
            "garden path lined with sunflowers to a blue door",
            "friends having tea in the garden under bunting as blank flags",
            "barn owl on the cottage roof at dusk",
            "winter cottage with a wreath and a stack of firewood",
        ],
    },
    "cozy-critters-40": {
        "prefix": "cri",
        "out_prefix": "cri",
        "title": "Cozy Critters",
        "subtitle": "40 Bold & Easy Animals with Personality",
        "one_liner": "Grumpy cats, capybaras, otters, and sloths living their best cozy lives.",
        "keywords": [
            "cute animals coloring book",
            "capybara coloring pages",
            "grumpy cat coloring",
            "otter coloring book",
            "sloth coloring book easy",
            "highland cow coloring",
            "bold and easy animal coloring",
        ],
        "query": "cozy animals capybara cat otter bold easy coloring book",
        "cover_rgb": ((255, 228, 200), (150, 90, 55)),
        "cover_accent": (255, 180, 90),
        "back_label": "Snuggle and color",
        "gradient": ((250, 214, 176), (148, 86, 50)),
        "scenes": [
            "grumpy cat with a coffee mug on a rainy windowsill",
            "capybara in a round hot spring with a flower crown",
            "highland cow portrait with a simple floral wreath",
            "axolotl with blush cheeks in a round bowl garden",
            "sloth in a hammock with a blank book and a plant",
            "two otters holding paws in a river",
            "penguin pair in winter scarves on ice",
            "red panda in bamboo with a round snack",
            "cat barista behind a tiny coffee bar no text",
            "dog librarian among stacked blank books",
            "grumpy cat Monday bed with a clock as a blank circle",
            "capybara napping under orange trees with friends",
            "highland cow in a meadow of large daisies",
            "axolotl wearing a tiny bow sitting on aquarium rocks",
            "sloth slow-living kitchen with bananas and a kettle",
            "otter couple sharing a clamshell picnic",
            "penguin waddle parade with scarves and a snow cottage",
            "red panda climbing with big easy bamboo leaves",
            "cat in rain boots under a mushroom umbrella",
            "corgi-like dog as a mail carrier with a blank bag",
            "rabbit baker with round buns no lettering",
            "bear in a bathrobe with cucumber slices on eyes",
            "fox in spectacles reading a blank book by a fire",
            "duck in a raincoat jumping in puddles",
            "koala hugging a mug in a eucalyptus window",
            "hedgehog with a backpack of flowers",
            "capybara with a bird sitting on its head in a spa",
            "two cats sharing a giant pancake",
            "otter floating with a teacup balanced on its belly",
            "penguin ice-cream stand with cone shapes no words",
            "highland cow wearing a knitted sweater in snow",
            "sloth yoga on a branch with hanging plants",
            "grumpy cat at a tiny desk with a blank calendar",
            "red panda picnic on a mushroom stool",
            "axolotl tea party with bubble cups",
            "dog gardener with a watering can and sunflowers",
            "cat painter at an easel with a heart on the canvas",
            "bunnies in pajamas having a moonlight feast",
            "otter family sliding down a riverbank",
            "all the critters napping together in a giant armchair",
        ],
    },
    "dragons-40": {
        "prefix": "drg",
        "out_prefix": "drg",
        "title": "Dragons",
        "subtitle": "40 Bold & Easy Mythical Friends to Color",
        "one_liner": "Baby dragons, elder wyrms, phoenixes, and cozy lairs in big bold outlines.",
        "keywords": [
            "dragon coloring book",
            "bold and easy dragons",
            "phoenix coloring pages",
            "mythical creatures coloring",
            "cute dragon coloring book",
            "fantasy dragon coloring",
            "simple dragon designs",
        ],
        "query": "dragons phoenix bold easy coloring book",
        "cover_rgb": ((30, 70, 70), (20, 40, 80)),
        "cover_accent": (180, 120, 255),
        "back_label": "Wake the dragon",
        "gradient": ((28, 90, 80), (40, 28, 90)),
        "scenes": [
            "tiny baby dragon hatching from an egg in a nest of flowers",
            "round baby dragon hugging a teacup",
            "small dragon sleeping on a pile of round coins",
            "baby dragon with a balloon as a blank circle",
            "two baby dragons sharing a marshmallow over a tiny fire",
            "dragon hatchling in a knitted scarf",
            "phoenix chick in a nest of simple flame shapes",
            "baby dragon looking in a castle window",
            "small dragon watering a garden with a watering can",
            "dragonet curled around a lantern",
            "dragon in mid-flight over rolling hills large wing plates",
            "elder dragon on a mountain with large simple scales",
            "phoenix rising among big flame petals and a sun",
            "dragon and phoenix circling a castle tower",
            "griffin perched on a cathedral roof",
            "friendly gargoyle on a library ledge with ivy",
            "dragon sleeping in a crystal cave",
            "sea dragon in a lagoon with large coral shapes",
            "unicorn watching a dragon from an enchanted grove",
            "fairy ring of large mushrooms with a tiny dragon",
            "dragon baking cookies in a cottage kitchen",
            "knight offering a cupcake to a shy dragon",
            "dragon hoard as large gems cups and a teapot",
            "ice dragon on a glacier with simple ice shards",
            "forest dragon covered in moss and flowers",
            "dragon flying over a village of round roofs",
            "phoenix in a blossoming tree at dawn",
            "dragon reading a blank book in a tower study",
            "two dragons playing with a ball of yarn",
            "dragon nest on a sea stack with chicks",
            "cave door with a round dragon knocker no letters",
            "dragon and a sheep napping in a meadow",
            "storm dragon above simple cloud hills",
            "tea party of four small dragons",
            "dragon crossing a stone bridge into a castle",
            "elder dragon teaching a baby to fly over trees",
            "jewel-cave dragon with large crystal towers",
            "dragon curled around a lighthouse",
            "night flight over a full moon and a quiet town",
            "huge friendly elder dragon smiling in a flower valley",
        ],
    },
    "spooky-cute-40": {
        "prefix": "spk",
        "out_prefix": "spk",
        "title": "Spooky Cute",
        "subtitle": "40 Bold & Easy Cozy Halloween Friends",
        "one_liner": "Adorable ghosts, pajama vampires, and pumpkin families in big bold outlines.",
        "keywords": [
            "spooky cute coloring book",
            "cute ghost coloring pages",
            "cozy halloween coloring",
            "bold and easy halloween",
            "pumpkin coloring book",
            "witch cat coloring",
            "spooky but cozy coloring",
        ],
        "query": "spooky cute cozy halloween bold easy coloring book",
        "cover_rgb": ((255, 210, 160), (90, 40, 80)),
        "cover_accent": (255, 160, 70),
        "back_label": "Boo, but make it cozy",
        "gradient": ((255, 196, 140), (88, 36, 78)),
        "scenes": [
            "round ghost in a blanket holding hot cocoa",
            "cute vampire in pajamas reading a blank book by a candle",
            "two friendly skeletons having tea",
            "jack-o-lantern with a happy face on a porch",
            "witch cat stirring a cauldron in a cottage kitchen",
            "haunted house with warm glowing windows not scary",
            "shy monster under the bed waving with a stuffed toy",
            "tiny ghost family on a sofa with a quilt",
            "pumpkin with a flower crown",
            "black cat in a witch hat napping",
            "ghost picnic with cocoa and cookies in a moonlit meadow",
            "vampire in fuzzy slippers at a candlelit desk",
            "skeleton tea party with a three-tier cake",
            "pumpkin family of varied friendly faces on a stoop",
            "witch cat kitchen with bottles that have leaf icons only",
            "haunted cottage path lined with smiling pumpkins",
            "cuddly monster invited up onto the bed for stories",
            "cemetery garden with flowers butterflies and a smiling ghost",
            "bat hanging from a cozy curtain with stars",
            "mummy wrapped loosely holding a mug",
            "werewolf in a robe brushing teeth at a sink",
            "ghost hanging laundry of little sheets",
            "pumpkin patch wagon ride with cute ghosts",
            "witch on a broom delivering pie to a cottage",
            "haunted library with friendly skeleton librarian blank books",
            "spider with a bow baking cookies",
            "moonlit pumpkin boat on a calm pond",
            "costume closet of hats and capes no text",
            "ghost roasting marshmallows with a vampire",
            "cat and ghost sharing a windowsill pie",
            "friendly scarecrow with a pumpkin friend",
            "trick-or-treat path of round houses with heart door knockers",
            "cauldron bubbling with large simple bubbles and veggies",
            "owl in a tiny witch hat on a fence",
            "skeleton band with drums as simple shapes no notes text",
            "haunted greenhouse of pumpkins and ferns",
            "ghost in a bubble bath with a rubber duck",
            "vampire garden of night flowers and a lantern",
            "monster tea in a treehouse",
            "whole spooky-cute town under a huge friendly moon",
        ],
    },
    "holidays-40": {
        "prefix": "hol",
        "out_prefix": "hol",
        "title": "Holidays",
        "subtitle": "40 Bold & Easy Seasonal Scenes to Color",
        "one_liner": "Christmas cottages, pumpkin porches, spring gardens, and cozy feast tables.",
        "keywords": [
            "holiday coloring book",
            "bold and easy christmas",
            "halloween cat coloring",
            "thanksgiving coloring pages",
            "valentines animals coloring",
            "seasonal coloring book adults",
            "easter garden coloring",
        ],
        "query": "bold and easy christmas holiday coloring book",
        "cover_rgb": ((180, 40, 45), (30, 70, 45)),
        "cover_accent": (255, 200, 90),
        "back_label": "Celebrate and color",
        "gradient": ((176, 42, 48), (28, 72, 48)),
        "scenes": [
            "christmas cottage with a wreath on the door and falling snow",
            "cat in a pumpkin costume on a porch",
            "two birds with a heart-shaped wreath for valentine",
            "easter bunny in a flower garden with eggs as plain ovals",
            "beach picnic with a watermelon and umbrella",
            "harvest table with a turkey platter of round vegetables",
            "snowman with a scarf and a cottage behind",
            "autumn leaf pile with a smiling child-like fox",
            "heart-shaped cookies on a cooling rack",
            "string of round ornaments on a tree no letters",
            "wreath-adorned cottage door in deep snow",
            "christmas kitchen with gingerbread house blank icing",
            "reindeer in a scarf by a stable",
            "cozy fireplace with stockings as blank shapes",
            "halloween cats in cute costumes not gory",
            "porch of pumpkins and autumn leaves",
            "autumn wreath of leaves acorns and a pumpkin",
            "owl in a harvest moon field",
            "valentine otters holding a big heart cookie",
            "lovebirds in a blooming window box",
            "easter garden party with bunnies and a tea table",
            "chick and bunny under a blossoming tree",
            "summer lemonade stand with lemon slices blank sign with a lemon icon",
            "beach umbrella picnic with a sandcastle",
            "fireworks as simple burst shapes over a lake cottage",
            "thanksgiving harvest table with pie and cornucopia shapes",
            "friends around a feast with a pumpkin centerpiece",
            "corn maze entrance with a scarecrow no lettering",
            "new year lanterns as round globes over a quiet street",
            "spring umbrellas and tulips after rain",
            "fourth-of-july picnic quilt of large squares and a pie",
            "hanukkah-like menorah as a simple candle holder with flames no text",
            "winter ice skating pond with a cocoa stand blank sign",
            "advent-style house with twenty-four blank windows no numbers",
            "christmas market stalls with wreaths and pretzels no words",
            "lunar new year-like lantern street with a friendly dragon dance",
            "diwali-like clay lamps in a rangoli floral pattern no text",
            "solstice bonfire with friends and a huge moon",
            "birthday picnic with a cake and blank banner flags",
            "four seasons tree in one scene: bloom leaf snow and fruit",
        ],
    },
    "chapel-gardens-40": {
        "prefix": "chp",
        "out_prefix": "chp",
        "title": "Chapel Gardens",
        "subtitle": "40 Bold & Easy Peaceful Sunday Scenes",
        "one_liner": "Quiet chapels, doves, olive groves, and garden paths in big bold outlines.",
        "keywords": [
            "christian coloring book",
            "chapel coloring pages",
            "dove coloring book",
            "inspirational coloring easy",
            "sunday school coloring adults",
            "peaceful church coloring",
            "bold and easy faith coloring",
        ],
        "query": "chapel dove garden bold easy coloring book",
        "cover_rgb": ((255, 230, 230), (120, 140, 100)),
        "cover_accent": (212, 175, 90),
        "back_label": "Walk in peace",
        "gradient": ((255, 220, 220), (110, 132, 92)),
        "scenes": [
            "small white chapel with a simple cross on the roof and a garden path",
            "dove with an olive branch over a hillside",
            "sunrise behind a quiet country church",
            "hands holding a round loaf of bread on a table",
            "candle still life with flowers",
            "shepherd with three sheep on a gentle hill",
            "olive tree and a stone bench",
            "lily bouquet in a chapel window alcove",
            "garden gate opening toward a chapel",
            "pair of doves on a fountain",
            "chapel exterior with climbing roses and a stone walk",
            "stained-glass chapel window as large simple panes from outside",
            "dove flying over an olive grove",
            "still life of grapes bread and a cup no lettering",
            "prayer garden with a round reflecting pool",
            "country baptism river with friends on the bank no text",
            "bell in a simple steeple among clouds",
            "nativity-like stable with animals and a star no words",
            "empty tomb garden at sunrise with flowers",
            "advent wreath of greenery and four candles no numbers",
            "easter lilies around a chapel door",
            "community picnic on chapel lawn",
            "choir loft as simple pews and a round window",
            "children's garden with a dove birdbath",
            "harvest altar of wheat and apples no signs",
            "mountain chapel in snow with a wreath",
            "desert chapel with cactus and a huge sky",
            "seaside chapel on a cliff with gulls",
            "woodland path of light toward a chapel",
            "hands planting a tree in a churchyard",
            "wedding arbor of flowers in a chapel garden",
            "open blank book on a lectern with a flower bookmark",
            "lamb sleeping under an olive tree",
            "sunrise cross on a distant hill as a simple shape",
            "community potluck table with pies and flowers",
            "bell tower with swallows nesting",
            "quiet pew interior with a hat and a hymnal as a blank book",
            "garden of gethsemane-like olive trees and a moon",
            "river of still water through green pastures with sheep",
            "chapel at dusk with lanterns along the path",
        ],
    },
    "slow-mornings-40": {
        "prefix": "slw",
        "out_prefix": "slw",
        "title": "Slow Mornings",
        "subtitle": "40 Bold & Easy Self-Care Scenes to Color",
        "one_liner": "Coffee, baths, journals, and gentle morning rituals in big bold outlines.",
        "keywords": [
            "self care coloring book",
            "morning routine coloring",
            "coffee coloring pages",
            "bold and easy cozy mornings",
            "bath coloring book",
            "mindfulness coloring easy",
            "self love scenes coloring",
        ],
        "query": "slow mornings self care bold easy coloring book",
        "cover_rgb": ((255, 228, 232), (180, 140, 170)),
        "cover_accent": (255, 200, 160),
        "back_label": "Breathe in, color on",
        "gradient": ((255, 220, 224), (176, 132, 164)),
        "scenes": [
            "mug of coffee on a sunny windowsill with a plant",
            "open blank journal and a pen on a quilt",
            "bathtub with bubbles and a rubber duck",
            "yoga cat stretching on a mat with a plant",
            "toast and berries on a round plate",
            "mirror with a flower wreath no writing",
            "teapot and two cups on a breakfast tray",
            "sunrise seen from bed with a sleeping cat",
            "face towel and a round compact on a vanity",
            "walking shoes and a water bottle by the door",
            "morning ritual trio: coffee blank journal and a flower",
            "deep soaking tub with candles and a window garden",
            "woman silhouette stretching toward a sunny window",
            "pancake breakfast in bed with a tiny vase",
            "balcony breakfast with a city of round roofs",
            "garden yoga among large flowers",
            "knitting in a window seat with tea",
            "skincare still life of bottles with leaf icons only",
            "picnic blanket morning in a meadow",
            "record player and a plant in a sunbeam",
            "smoothie bowl with fruit shapes on a table",
            "rainy morning reading nook with a blank book",
            "cat supervising breakfast from the counter",
            "open window with billowing curtains and birds",
            "farmer-market tote of flowers and bread",
            "hammock on a porch at sunrise",
            "bath caddy with a teacup and a blank book",
            "sunrise hike hill with a thermos",
            "friends brunch table with pastries no menus",
            "pottery mug-making on a wheel",
            "houseplant watering morning with a watering can",
            "mirror selfie scene as a person smiling no phone text",
            "gratitude table: vase, candle, blank card with a heart",
            "night-before layout of clothes and a flower",
            "cozy robe and slippers by a heater stove",
            "orange juice and a newspaper as a blank folded stack",
            "beach sunrise walk with a dog",
            "cabin morning with pancakes and a lake view",
            "meditation cushion by a round window of sky",
            "huge lazy Sunday bed with books tea and a dog",
        ],
    },
    "moon-magic-40": {
        "prefix": "mmg",
        "out_prefix": "mmg",
        "title": "Moon Magic",
        "subtitle": "40 Bold & Easy Witchy Night Scenes",
        "one_liner": "Moons, crystals, herb cottages, and cozy cauldrons in big bold outlines.",
        "keywords": [
            "witchy coloring book",
            "moon phase coloring",
            "crystal coloring pages",
            "celestial coloring book easy",
            "cottage witch coloring",
            "tarot aesthetic coloring",
            "bold and easy pagan coloring",
        ],
        "query": "witchy moon crystals bold easy coloring book",
        "cover_rgb": ((30, 24, 50), (80, 40, 90)),
        "cover_accent": (212, 175, 90),
        "back_label": "Light the candles",
        "gradient": ((28, 22, 48), (86, 40, 96)),
        "scenes": [
            "crescent moon over a cottage with a cat on the roof",
            "cluster of crystals on a cloth with a candle",
            "cauldron over a tiny hearth with a wooden spoon",
            "herb hanging bundles in a kitchen no labels",
            "round card with a moon icon on a table not a famous tarot",
            "cat witch with a hat stirring tea",
            "windowsill crystals catching moonlight",
            "simple star map as dots and lines over hills no names",
            "broom leaning by a cottage door with flowers",
            "full moon reflected in a cauldron",
            "eight moon phases as large moons along a hillside path no numbers",
            "amethyst and quartz still life with a wooden bowl",
            "herb cottage interior with drying racks and a kettle",
            "generic card spread of three blank-backed moon cards",
            "pentacle as a wooden charm on a floral tablecloth in a scene",
            "goddess-like figure silhouette filled with leaves and stars",
            "spell ingredients as mushrooms herbs and bottles with leaf icons",
            "constellation night over a round stone circle",
            "crystal cave with a witch lantern",
            "moon garden of night blooms and a black cat",
            "tarot-cloth table with candles crystals and a teacup",
            "owl familiar on a stack of blank grimoire books",
            "outdoor ritual of friends around a small fire and moon",
            "mortar and pestle with herbs on a cutting board",
            "stained-glass moon in a witch cottage window",
            "potion shelf of round bottles with flower stoppers no text",
            "flying over a sleeping town on a broom with a basket",
            "scrying bowl of water reflecting a moon and trees",
            "mushroom circle with a tiny witch picnic",
            "altar of seashells candles and a bowl of salt as simple shapes",
            "winter solstice cottage with evergreens and a huge moon",
            "summer herb harvest with a wicker basket",
            "crystal shop interior blank signs with a crystal icon only",
            "cat sleeping inside a huge crescent moon cushion",
            "rainy witch window with tea and a blank book",
            "starry lake with a canoe and a lantern",
            "sun and moon faces as friendly simple faces over a garden",
            "witch greenhouse of strange friendly plants",
            "full-moon market of crystal stalls and pies no lettering",
            "midnight cottage kitchen, cauldron, cat, and a pie cooling",
        ],
    },
    "dark-academia-40": {
        "prefix": "aca",
        "out_prefix": "aca",
        "title": "Dark Academia",
        "subtitle": "40 Bold & Easy Gothic Study Scenes",
        "one_liner": "Libraries, typewriters, candlelit desks, and ivy courtyards in big bold outlines.",
        "keywords": [
            "dark academia coloring book",
            "gothic library coloring",
            "vintage study coloring",
            "bold and easy academia",
            "university courtyard coloring",
            "typewriter coloring page",
            "cozy gothic coloring book",
        ],
        "query": "dark academia gothic library bold easy coloring book",
        "cover_rgb": ((70, 40, 30), (30, 20, 20)),
        "cover_accent": (212, 175, 90),
        "back_label": "Study and color",
        "gradient": ((72, 42, 32), (28, 18, 18)),
        "scenes": [
            "tall bookshelf and a rolling ladder in a cozy aisle",
            "vintage typewriter and an ink bottle on a desk",
            "candle and an open blank book",
            "ivy-covered bust on a pedestal",
            "rainy university courtyard with an arch",
            "skull with two roses on a cloth",
            "antique globe on a stand",
            "chess board with a few large pieces and tea",
            "espresso cup and a folded blank newspaper",
            "trench coat on a café chair",
            "floor-to-ceiling library with a spiral stair and a cat",
            "candlelit desk with leather blank books and a quill",
            "typewriter still life with papers as blank sheets",
            "greek-style bust with ivy in a study alcove",
            "cobblestone courtyard in rain with umbrellas",
            "vanitas of skull roses candle and an hourglass",
            "maps and a globe on a library table no place names",
            "literary café with espresso blank papers and a coat",
            "chess game by a fireplace with two armchairs",
            "stained-glass reading room with a huge window",
            "dormer attic study with a telescope",
            "museum hall of simple statues and a skylight",
            "botanical library with plant sketches as blank pages",
            "night library with a single lamp and rain on the glass",
            "lecture hall as simple benches and a round chalkboard blank",
            "fountain in a college quad with autumn leaves",
            "wax seal and letters as blank envelopes with a heart",
            "phonograph and a stack of records",
            "greenhouse attached to a brick library",
            "bridge of sighs-like covered walk in rain",
            "cat asleep on a pile of blank theses",
            "midnight snack of tea and toast in the stacks",
            "observatory dome with a huge moon window",
            "calligraphy desk with a quill and ink no letters written",
            "cloakroom of coats hats and a wet umbrella",
            "stone spiral staircase with a lantern",
            "friends studying at a long table with a shared lamp",
            "window seat overlooking a gothic quad",
            "secret door in a bookshelf slightly ajar",
            "sunrise through library windows onto empty chairs and coffee",
        ],
    },
    "corgis-40": {
        "prefix": "crg",
        "out_prefix": "crg",
        "title": "Corgis",
        "subtitle": "40 Bold & Easy Pembroke Days to Color",
        "one_liner": "Sploots, garden helpers, couch kings, and costume corgis in big bold outlines.",
        "keywords": [
            "corgi coloring book",
            "pembroke corgi coloring",
            "dog coloring book easy",
            "bold and easy corgi",
            "cute corgi pages",
            "pet coloring book corgi",
            "corgi sploot coloring",
        ],
        "query": "corgi coloring book bold easy",
        "cover_rgb": ((255, 220, 180), (140, 80, 40)),
        "cover_accent": (255, 170, 80),
        "back_label": "Sploot and color",
        "gradient": ((255, 210, 170), (138, 78, 38)),
        "scenes": [
            "one corgi sploot on a rug smiling",
            "corgi butt facing a garden gate",
            "corgi on a couch with a remote as a blank rectangle",
            "corgi in a birthday cone hat",
            "corgi with a rubber duck in a kiddie pool",
            "corgi watching rain from a window",
            "corgi in a sweater on a walk",
            "corgi sleeping in a dog bed with a bone",
            "corgi with a flower crown",
            "corgi catching a round ball",
            "corgi gardener with a watering can among sunflowers",
            "corgi yoga with a person stretching on a mat",
            "corgi in a café under the table with a biscuit",
            "two corgis sharing a giant pretzel",
            "corgi in seasonal costumes: pumpkin then scarf as one scene closet",
            "corgi herding three round sheep on a hill",
            "corgi at the beach with a sandcastle",
            "corgi in a backpack looking over a shoulder toward mountains",
            "corgi bakery helper with flour on its nose",
            "corgi reading nook on an armchair",
            "corgi snow day with a tiny shovel",
            "corgi autumn leaf pile dive",
            "multi-pet nap: corgi and a cat on a sofa",
            "corgi in a car passenger seat with a map as a blank fold",
            "corgi farmers market with a basket of bread",
            "corgi camping tent and a marshmallow stick",
            "corgi wedding flower dog with a bow",
            "corgi at a bookshop among blank books",
            "corgi sunset hill looking at a gentle rainbow arc",
            "pack of corgis running through a meadow",
            "corgi in a raincoat jumping in puddles",
            "corgi birthday picnic with a bone-shaped cake",
            "corgi on a paddleboard on a calm lake",
            "corgi and a hen in a cottage garden",
            "corgi window shopping a bakery with pies",
            "corgi under a Christmas tree with a wreath collar",
            "corgi stroller ride in a flower park",
            "senior corgi on a porch swing",
            "corgi howling at a friendly huge moon",
            "corgi family of four napping in a sunbeam",
        ],
    },
    "zen-gardens-40": {
        "prefix": "zen",
        "out_prefix": "zen",
        "title": "Zen Gardens",
        "subtitle": "40 Bold & Easy Japanese Garden Scenes",
        "one_liner": "Koi ponds, bamboo paths, torii, and tea pavilions in big bold outlines.",
        "keywords": [
            "zen garden coloring book",
            "japanese garden coloring",
            "koi pond coloring pages",
            "bamboo coloring book",
            "torii coloring book easy",
            "sakura coloring pages",
            "mindfulness garden coloring",
        ],
        "query": "zen garden koi bamboo bold easy coloring book",
        "cover_rgb": ((210, 220, 210), (80, 110, 100)),
        "cover_accent": (180, 200, 170),
        "back_label": "Sit and color",
        "gradient": ((200, 214, 200), (70, 100, 92)),
        "scenes": [
            "overhead koi pond with two fish and three lily pads",
            "bamboo path with a simple gate",
            "one torii at the end of a pebble path",
            "cherry blossom branch with a round moon",
            "bonsai in a simple pot on a bench",
            "tea bowl and whisk on a tatami-like mat",
            "stone lantern beside a maple",
            "raked sand as three large concentric arcs around one rock",
            "stepping stones across a tiny stream",
            "pagoda roof among pines",
            "koi pond with stepping stones and a wooden bridge",
            "bamboo forest path with light shafts and a traveler",
            "pagoda garden with a pond and maples",
            "torii standing in shallow water at sunrise",
            "sakura tunnel over a path with petals",
            "rock garden of three large stones and wide sand swirls",
            "bonsai display on a porch with a kettle",
            "tea ceremony still life: kettle bowl sweets as round cakes",
            "zen monk as a simple robed figure raking sand",
            "moon-viewing deck with a huge moon and pines",
            "tsukubai water basin with a bamboo spout",
            "koi leaping near a stone lantern",
            "autumn maple viewing platform over a pond",
            "snow garden with a stone lantern cap of snow",
            "iris garden along a wooden walkway",
            "shrine steps with a simple rope and paper zigzags no writing",
            "indoor tokonoma alcove with a vase and a blank scroll",
            "boat on a misty lake toward a torii",
            "crane standing in reeds at dawn",
            "friend sharing tea in a garden pavilion",
            "pebble beach with a torii and distant mountain",
            "moss garden with a winding path",
            "wind chime of simple shapes under eaves",
            "carp streamers as blank fish shapes on poles no text",
            "night garden with hanging round lanterns",
            "bridge zigzag over a lotus pond",
            "studio looking onto a raked garden",
            "cat sleeping on a veranda beside tea cups",
            "mountain temple approached through fog and pines",
            "full-frame koi pond garden with pavilion and cherry tree",
        ],
    },
    "retro-40": {
        "prefix": "rtr",
        "out_prefix": "rtr",
        "title": "Retro Days",
        "subtitle": "40 Bold & Easy Vintage Scenes to Color",
        "one_liner": "Diners, camper vans, vinyl nights, and seaside poster views in big bold outlines.",
        "keywords": [
            "retro coloring book",
            "1950s diner coloring",
            "vintage travel coloring",
            "art deco coloring easy",
            "camper van coloring book",
            "vinyl record coloring",
            "bold and easy retro",
        ],
        "query": "retro diner vintage travel bold easy coloring book",
        "cover_rgb": ((245, 230, 200), (140, 70, 50)),
        "cover_accent": (220, 160, 70),
        "back_label": "Then and now, color",
        "gradient": ((240, 220, 186), (138, 68, 48)),
        "scenes": [
            "diner booth with a milkshake and a jukebox",
            "checkered diner floor with a round stool counter",
            "camper van on a desert road",
            "vinyl record on a turntable",
            "mid-century armchair and a starburst clock as a blank star",
            "ice cream soda fountain",
            "drive-in speaker on a car window",
            "lighthouse travel-poster seaside no lettering",
            "art deco theater marquee as blank shapes with lights",
            "roller skates beside a milkshake",
            "1950s diner interior with jukebox milkshakes and booths",
            "art deco hotel facade with fan windows as a street scene",
            "national-park-style canyon overlook no poster text",
            "seaside resort boardwalk with a ferris wheel",
            "mid-century living room with a boomerang table and lamp",
            "retro camper van picnic at a lake",
            "tasteful vintage fashion figure in a polka-dot dress on a boardwalk",
            "record shop bins of vinyl and a listening booth",
            "1970s van with a rainbow stripe and daisies",
            "1980s boom box and cassette as simple shapes on a blanket",
            "gas station with a cute rounded pump blank brand",
            "motel pool with a diving board and palm",
            "diner kitchen pass-through with pies",
            "bowling alley with large pins and a ball",
            "drive-through burger tray on a car window",
            "tiki patio with a pineapple drink no logos",
            "train streamliner arriving at a small station",
            "carousel with simple horses",
            "soda advertisement homage as a bottle still life no slogans",
            "sunburst clock wall over a cocktail bar of simple glasses",
            "tailfin car at a sunset diner",
            "roller rink under string lights",
            "photo booth as a simple box with a curtain heart photos blank",
            "highway motor court with neon as blank tubes",
            "surfboards at a 60s beach shack",
            "typewriter and a rotary phone on a desk",
            "cinema popcorn machine and two tickets as blank stubs",
            "christmas downtown 1950s with wreaths and a tree",
            "family station wagon packed for a road trip",
            "night diner from outside with a huge moon and empty booths glowing",
        ],
    },
    "rest-easy-40": {
        "prefix": "rst",
        "out_prefix": "rst",
        "title": "Rest Easy",
        "subtitle": "40 Bold & Easy Calming Scenes to Color",
        "one_liner": "Waves, meadows, rainy windows, and quiet paths in big bold outlines.",
        "keywords": [
            "anxiety relief coloring book",
            "calming coloring pages",
            "easy stress relief coloring",
            "wave pattern coloring",
            "rainy window coloring",
            "bold and easy calm",
            "mindfulness scenes coloring",
        ],
        "query": "anxiety relief easy calm coloring book",
        "cover_rgb": ((200, 220, 230), (70, 110, 120)),
        "cover_accent": (180, 210, 190),
        "back_label": "Rest here a while",
        "gradient": ((190, 214, 224), (64, 104, 116)),
        "scenes": [
            "simple rolling waves and a round sun",
            "one cloud over a quiet meadow path",
            "rainy window with a teacup on the sill",
            "hammock between two trees by a lake",
            "ring of round stones in shallow water",
            "sleeping cat in a sunbeam",
            "open gate to a gentle hill",
            "cup of tea steaming on a blanket",
            "rowboat tied to a quiet dock",
            "candle and a plant on a nightstand",
            "wide calm ocean with large simple wave bands",
            "meadow path toward a distant cottage",
            "rainy cafe window with a blank book",
            "lake kayak at sunrise with reeds",
            "garden labyrinth of large hedge curves",
            "hot spring pool with steam curls and stones",
            "cloudy sky of big friendly cloud shapes",
            "shoreline with tide pools and a starfish",
            "wind in tall grass with a single tree",
            "moonlit still water with a dock lantern",
            "porch rain with a rocking chair and a quilt",
            "snow falling on a quiet street of round roofs",
            "underwater-like kelp as large ribbons and a friendly fish",
            "desert dusk with three simple hills and a moon",
            "orchard path in blossom",
            "library window seat with rain and tea",
            "mountain lake mirror with one canoe",
            "field of lavender rows toward a shed",
            "night train window of dark hills as simple shapes",
            "greenhouse quiet with hanging plants",
            "stone steps down to a beach at low tide",
            "friends sitting silently on a dock with dangling feet",
            "cat and dog asleep in a basket",
            "open umbrella over a garden bench in light rain",
            "sunrise yoga silhouette on a cliff of large rocks",
            "wind chimes and curtains in a breeze",
            "lily pads on a perfectly still pond",
            "camp at dusk with a small fire and a huge sky",
            "blanketed figure looking out at snow",
            "wide empty beach at golden hour with footprints and a shell",
        ],
    },
    "dinosaurs-40": {
        "prefix": "dino",
        "out_prefix": "dino",
        "title": "Dinosaurs",
        "subtitle": "40 Bold & Easy Prehistoric Friends to Color",
        "one_liner": "Friendly long-necks, feathered hunters, and nest scenes in big bold outlines.",
        "keywords": [
            "dinosaur coloring book",
            "bold and easy dinosaurs",
            "cute dino coloring pages",
            "t-rex coloring book easy",
            "triceratops coloring",
            "kids dinosaur coloring adults",
            "simple dinosaur designs",
        ],
        "query": "dinosaurs bold easy coloring book",
        "cover_rgb": ((210, 220, 170), (80, 100, 50)),
        "cover_accent": (255, 180, 80),
        "back_label": "Walk with giants",
        "gradient": ((200, 214, 160), (76, 96, 46)),
        "scenes": [
            "one round baby long-neck dinosaur under a palm",
            "triceratops face portrait with three horns simple",
            "tiny dinosaur hatching from an egg",
            "stegosaurus with large plates in a meadow",
            "pterosaur gliding over a simple sea",
            "two dinos sharing a giant leaf",
            "dinosaur footprint puddle with a small dino looking in",
            "ankylosaurus as a round armored friend",
            "dinosaur sleeping in a flower nest",
            "long-neck eating from a tall tree",
            "herd of long-necks crossing a river",
            "triceratops family at a watering hole",
            "feathered raptor pair hunting a butterfly not gory",
            "t-rex sneezing flowers in a meadow cute",
            "dinosaur nest with three eggs and a parent",
            "volcano as a simple cone with dinos in a fern valley",
            "swimming long-necked marine reptile with large fins",
            "dinosaur and a waterfall jungle",
            "night of fireflies and sleeping dinos",
            "dinosaur parade across a log bridge",
            "spinosaurus fishing in a river with a huge sail",
            "parasaurolophus calling with a crest by a lake",
            "dino and a volcano sunset",
            "baby dinos playing with a vine swing",
            "armored dinosaur garden of cycads",
            "pterosaur colony on sea cliffs",
            "dinosaur in the rain with a leaf umbrella",
            "two dinos racing along a beach",
            "dinosaur museum-like hall of friendly statues no plaques",
            "time-agnostic picnic of dinos and a blanket of fruit",
            "snowy dinosaur in a pine valley",
            "desert dinos among big bones as simple shapes",
            "jungle canopy with a climbing little dino",
            "dinosaur crossing stepping stones",
            "parent dino sheltering babies under a sail-like frill",
            "meteor as a distant star streak over peaceful dinos not scary",
            "oasis with dinos and palm ferns",
            "cave paintings of dinos as simple outlines on a wall",
            "dinosaur looking at its reflection in a pond",
            "valley of giants under a huge friendly sun",
        ],
    },
    "star-signs-40": {
        "prefix": "zdc",
        "out_prefix": "zdc",
        "title": "Star Signs",
        "subtitle": "40 Bold & Easy Zodiac Nights to Color",
        "one_liner": "Rams, lions, fishes, and constellation gardens in big bold outlines.",
        "keywords": [
            "zodiac coloring book",
            "astrology coloring pages",
            "star sign coloring book",
            "bold and easy zodiac",
            "constellation coloring",
            "leo lion coloring",
            "all signs coloring book",
        ],
        "query": "zodiac star signs bold easy coloring book",
        "cover_rgb": ((25, 30, 70), (80, 40, 90)),
        "cover_accent": (255, 210, 120),
        "back_label": "Follow your stars",
        "gradient": ((24, 28, 72), (78, 38, 88)),
        "scenes": [
            "ram on a rocky hill under a crescent moon",
            "bull in a flower meadow",
            "two twins flying kites under stars",
            "crab on a beach with a huge moon",
            "lion with a floral mane on a savanna night",
            "maiden with wheat in a harvest field",
            "balance scale as a garden sculpture among roses",
            "scorpion as a cute desert friend under stars",
            "archer centaur-like figure aiming at a blank circle moon",
            "sea-goat on a cliff above waves",
            "water bearer pouring stars into a pond",
            "two fish circling a coral garden",
            "ram leaping through a ring of spring flowers",
            "bull napping in a terracotta courtyard",
            "twins sharing a telescope on a roof",
            "crab lighthouse picnic",
            "lion sleeping in a sun garden",
            "maiden reading a blank book in an herb spiral",
            "scales hanging from a tree with two birds",
            "scorpion and cactus moon",
            "archer campfire in the hills",
            "sea-goat lighthouse in snow",
            "water bearer fountain in a night plaza",
            "fish pair in a lily pond from above",
            "twelve animal friends at a round table no text",
            "constellation night as dots connected over a cottage",
            "sun moon and a rising balloon as a blank circle",
            "birth-month bouquet of mixed blooms in a window",
            "wheel of the year as a circular garden path of four trees",
            "observatory hill with a lion and a telescope",
            "boat of fishes under the milky way as dotted bands",
            "twins in a library of star globes",
            "maiden and a bull sharing apples",
            "archer and ram on a mountain path",
            "scorpion and crab at a tide pool",
            "lion and water bearer at a city fountain",
            "sea-goat and fishes in a moonlit bay",
            "all twelve creatures napping in a giant crescent moon",
            "star map mural on a cottage wall as dots no letters",
            "midnight carnival of zodiac floats as animal parade no signs",
        ],
    },
}
