# Scene lists for bold-and-easy 40-page books (STYLE.md).
# Each entry is the SUBJECT only — prompts always wrap with the style prefix and NO TEXT.

STYLE_PREFIX = (
    "Square coloring-book line art, bold and easy cozy style like Quiet Places. "
    "Medium-weight clean closed black outlines on pure white background. "
    "No solid black fills, no shading, no gray, no hatching. "
    "Absolutely NO letters, NO words, NO numbers, NO readable text or signage. "
    "Fill the entire square frame with one cohesive illustrated scene. "
    "Cute hand-drawn look, large simple shapes, easy to color. "
)

THEMES = {
    "stained-glass-40": {
        "prefix": "sg",
        "out_prefix": "sg2",
        "title": "Stained Glass",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Window panels, roses, animals, and geometric glass patterns in big bold outlines.",
        "keywords": [
            "stained glass coloring book",
            "bold and easy coloring",
            "window patterns coloring",
            "stress relief coloring",
            "simple stained glass designs",
            "adult coloring bold lines",
            "glass pattern coloring book",
        ],
        "query": "stained glass bold easy coloring book",
        "cover_rgb": ((230, 220, 245), (70, 40, 110)),
        "cover_accent": (255, 200, 120),
        "back_label": "Color the light",
        "gradient": ((210, 195, 240), (80, 45, 120)),
        "scenes": [
            "rose window with petal segments and center circle",
            "tall cathedral arch window with simple geometric panes",
            "butterfly made of stained glass wing panels",
            "sunflower stained glass panel with radiating petals",
            "owl portrait in stained glass segments",
            "lotus flower stained glass medallion",
            "tree of life stained glass with simple branches and leaves",
            "heart medallion of leaded glass shapes",
            "peacock with stained glass fan tail segments",
            "dragonfly stained glass with wing panes",
            "moon and stars stained glass night panel",
            "fish swimming stained glass oval window",
            "tulip bouquet in stained glass vase panel",
            "geometric diamond lattice stained glass",
            "circular mandala-like stained glass without tiny detail",
            "birdhouse and bird stained glass scene",
            "sailboat on water stained glass panel",
            "mountain and sun stained glass landscape window",
            "cat silhouette filled with stained glass patches",
            "mushroom cottage stained glass fairy panel",
            "honeycomb hex stained glass pattern (large cells only)",
            "seashell stained glass spiral panel",
            "hot air balloon stained glass sky panel",
            "lantern with stained glass sides glowing shape only no fill",
            "garden gate with stained glass flowers above",
            "unicorn head stained glass portrait simple",
            "whale stained glass ocean panel",
            "pumpkin and leaves autumn stained glass",
            "snowflake large stained glass crystal",
            "coffee cup and steam stained glass cozy panel",
            "bicycle with flower basket stained glass",
            "lighthouse and waves stained glass",
            "fox stained glass forest portrait",
            "pineapple stained glass tropical panel",
            "umbrella and raindrops stained glass",
            "teapot and cup stained glass still life",
            "camper van stained glass travel panel",
            "sunflower field row as stained glass strips",
            "angel fish reef stained glass",
            "simple house facade stained glass window collage",
        ],
    },
    "cars-40": {
        "prefix": "car",
        "out_prefix": "car2",
        "title": "Cars",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Cute cars, trucks, and road scenes in big bold outlines for easy coloring.",
        "keywords": [
            "cars coloring book",
            "bold and easy cars",
            "truck coloring pages",
            "vehicle coloring book kids",
            "simple car designs",
            "stress relief coloring cars",
            "automobile coloring book",
        ],
        "query": "cars trucks bold easy coloring book",
        "cover_rgb": ((230, 235, 245), (30, 60, 120)),
        "cover_accent": (255, 180, 70),
        "back_label": "Hit the road",
        "gradient": ((180, 210, 245), (30, 70, 130)),
        "scenes": [
            "cute round compact car parked on a quiet street with trees",
            "classic convertible with flowers in the back seat",
            "school bus on a country road with hills",
            "fire truck with ladder and cute details no text",
            "ice cream truck with cone icons only no words",
            "pickup truck with pumpkins in the bed autumn",
            "vintage VW-style beetle with flowers",
            "police car cute rounded style no badges text",
            "taxi cab rounded cozy style no lettering",
            "camper van at a campsite with tent and trees",
            "sports car on a winding coastal road",
            "monster truck jumping over dirt mounds",
            "racecar on a simple track with checkered flags as shapes no text",
            "delivery van with heart logo only",
            "tractor on a farm with barn and fields",
            "jeep on a mountain trail with pines",
            "family station wagon packed for vacation with suitcases",
            "hot rod with big wheels and flame shapes on body as outlines",
            "electric car charging at a cute home charger",
            "limousine with balloons floating nearby",
            "tow truck helping a small broken car",
            "garbage truck with smiling face style cute",
            "cement mixer truck on a construction lot",
            "food truck park scene with picnic tables no menus text",
            "car wash scene with soap bubbles and brushes",
            "drive-in movie car facing a blank screen shape",
            "parking garage ramp with two cute cars",
            "road trip car and trailer overlooking a canyon",
            "snowy car with ski rack and pine trees",
            "beach buggy near dunes and surfboard",
            "taxi line outside a train station building exterior",
            "car ferry boarding with ocean waves",
            "mechanic garage with car on a lift cozy",
            "parade car covered in flowers float style",
            "go-kart track with two karts",
            "ambulance cute rounded emergency vehicle no text",
            "mail truck at suburban mailboxes no text",
            "car under a starry night camping overlook",
            "classic muscle car at a diner exterior no neon text",
            "two cars racing side by side on a desert highway",
        ],
    },
    "planes-40": {
        "prefix": "pln",
        "out_prefix": "pln2",
        "title": "Planes",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Airplanes, airports, and sky adventures in big bold easy outlines.",
        "keywords": [
            "planes coloring book",
            "airplane coloring pages",
            "bold and easy aviation",
            "airport coloring book",
            "flying machines coloring",
            "kids plane coloring",
            "stress relief planes coloring",
        ],
        "query": "airplanes bold easy coloring book",
        "cover_rgb": ((220, 235, 250), (40, 90, 150)),
        "cover_accent": (255, 200, 90),
        "back_label": "Up in the clouds",
        "gradient": ((190, 220, 245), (40, 90, 150)),
        "scenes": [
            "propeller plane flying over rolling hills and clouds",
            "passenger jet taking off from runway with control tower",
            "biplane looping above a meadow",
            "seaplane landing on a calm lake with mountains",
            "hot air balloon festival multiple balloons no text",
            "helicopter over a city skyline simple buildings",
            "glider soaring above cliffs by the ocean",
            "cargo plane loading at an airport hangar",
            "paper airplane flock over a park (large simple)",
            "private jet on a tarmac with mountains behind",
            "crop duster over farm fields and barn",
            "space shuttle style plane on a runway (simple)",
            "airplane window view of wing and clouds from inside outline",
            "airport terminal exterior with planes parked",
            "vintage triplane in a museum hangar",
            "flight of three jets in formation in clear sky",
            "plane flying over tropical islands and ocean",
            "ski plane landing on snowy runway with pines",
            "blimp floating over a fairground ferris wheel",
            "drone style small aircraft above a garden (simple cute)",
            "airplane pulling a blank banner (empty white rectangle no letters)",
            "kids toy plane on a bedroom shelf with clouds mural",
            "hangar doors open revealing a shiny plane",
            "plane flying through a rainbow over countryside",
            "night flight plane among stars and moon",
            "airplane over the grand canyon style cliffs",
            "floatplane docked at a wooden pier village",
            "pilot waving from open cockpit biplane cute no text",
            "runway lights and plane landing at dusk clouds",
            "airplane and airport luggage cart cute scene",
            "plane flying past a lighthouse coast",
            "stunt plane with smoke trails as outline swirls",
            "airplane over autumn forest canopy",
            "jet over desert dunes and cactus",
            "plane crossing above a suspension bridge city",
            "airplane cabin cozy seats aisle view simple no screens text",
            "control tower close-up with plane ascending",
            "plane flying beside migrating birds silhouette",
            "amphibious plane near waterfall jungle lake",
            "vintage travel poster style plane and globe as outlines no text",
        ],
    },
    "buildings-40": {
        "prefix": "bld",
        "out_prefix": "bld2",
        "title": "Buildings",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Cozy houses, shops, castles, and city scenes in big bold outlines.",
        "keywords": [
            "buildings coloring book",
            "houses coloring pages",
            "bold and easy architecture",
            "city coloring book",
            "cottage coloring",
            "castle coloring book easy",
            "cozy buildings coloring",
        ],
        "query": "buildings houses bold easy coloring book",
        "cover_rgb": ((235, 228, 220), (90, 70, 55)),
        "cover_accent": (255, 190, 120),
        "back_label": "Color the skyline",
        "gradient": ((230, 220, 210), (90, 70, 55)),
        "scenes": [
            "cozy cottage with flower boxes and stone path",
            "tall city skyscraper street scene with a few buildings",
            "fairytale castle with turrets and flags as blank shapes",
            "bakery storefront with cakes in window no text signs",
            "lighthouse on rocky shore at sunset clouds",
            "treehouse connected between two big trees",
            "barn and silo on a farm with fence",
            "japanese-style pagoda in a garden with lanterns",
            "library building with wide steps and columns no lettering",
            "fire station with garage doors and truck peeking",
            "beach house on stilts with palm trees",
            "mountain chalet with snow and pine trees",
            "windmill beside tulip fields",
            "train station platform with clock face no numbers readable blur as blank circle",
            "greenhouse glass house full of plants",
            "covered bridge over a creek in autumn",
            "downtown row of shop fronts awnings blank signs with hearts only",
            "museum building with grand staircase",
            "observatory dome on a hill under stars",
            "water tower and small town houses",
            "apartment balcony garden with hanging plants",
            "schoolhouse with playground swings no text",
            "harbor warehouse and fishing boats",
            "igloo village with northern lights swirls",
            "desert adobe pueblo style homes",
            "victorian house with wraparound porch",
            "modern glass house in a forest clearing",
            "clock tower square with fountain no readable clock numbers use blank face",
            "stadium exterior simple bold arches",
            "temple steps with statues simple garden",
            "factory with smokestacks stylized cute clouds",
            "motel courtyard poolside lounge chairs no neon text",
            "cabin in the woods with smoke from chimney",
            "bridge and gatehouse medieval town",
            "skyscraper rooftop garden with city view",
            "boathouse on a lake with canoe",
            "post office building cute with mailbox no text",
            "art gallery exterior with sculptures outside",
            "hospital building friendly rounded architecture no signs text",
            "spaceport terminal futuristic simple building and rocket",
        ],
    },
    "food-40": {
        "prefix": "food",
        "out_prefix": "food2",
        "title": "Food",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Cute meals, desserts, and picnic spreads in big bold easy outlines.",
        "keywords": [
            "food coloring book",
            "dessert coloring pages",
            "bold and easy food",
            "picnic coloring book",
            "cute food coloring",
            "snack coloring pages",
            "stress relief food coloring",
        ],
        "query": "food desserts bold easy coloring book",
        "cover_rgb": ((255, 235, 220), (160, 70, 50)),
        "cover_accent": (255, 210, 100),
        "back_label": "Dig in and color",
        "gradient": ((255, 230, 210), (170, 80, 55)),
        "scenes": [
            "stack of pancakes with butter and berries on a plate",
            "pizza with fun toppings on a wooden board",
            "ice cream sundae with cherry and whipped cream",
            "sushi platter with chopsticks and wasabi shapes",
            "burger and fries basket picnic style",
            "taco trio with lime and salsa bowls",
            "donut box open with assorted iced donuts no text",
            "fruit bowl overflowing with apples bananas grapes",
            "birthday cake with candles and sprinkles no writing on cake",
            "ramen bowl with egg chopsticks and steam",
            "picnic blanket spread with sandwiches and lemonade pitcher",
            "waffle with strawberries and syrup drizzle outlines",
            "hot cocoa mug with marshmallows and cookies",
            "avocado toast and soft boiled egg breakfast plate",
            "popcorn bucket and movie snacks cozy (blank bucket no text)",
            "cheese board with grapes crackers and honey jar",
            "smoothie bowls with kiwi blueberry toppings",
            "bbq grill with corn and veggies outdoors",
            "cupcake tower display stand",
            "spaghetti and meatballs with garlic bread",
            "croissant and coffee cup cafe table still life",
            "watermelon slice picnic with ants cute",
            "cookie jar overflowing with cookies",
            "breakfast burrito and salsa scene",
            "dim sum steamer baskets open",
            "pineapple upside down cake on a cake stand",
            "nachos platter with cheese and jalapeños",
            "tea time tray with scones and jam jars",
            "fish and chips newspaper wrap as blank paper texture no text",
            "salad bowl with veggies and dressing drizzle",
            "macaron tower pastel pastry shop window",
            "corn dogs and fair food booth no signage text",
            "oatmeal bowl with banana and cinnamon sticks",
            "grilled cheese and tomato soup cozy",
            "churros and chocolate dipping cup",
            "poke bowl with mango and avocado",
            "pumpkin pie slice thanksgiving table",
            "cotton candy and caramel apple carnival snacks",
            "veggie garden harvest basket overflow",
            "chocolate fountain with fruit skewers party table",
        ],
    },
    "mountains-40": {
        "prefix": "mtn",
        "out_prefix": "mtn2",
        "title": "Mountains",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Peaks, trails, lakes, and alpine cabins in big bold easy outlines.",
        "keywords": [
            "mountains coloring book",
            "nature landscape coloring",
            "bold and easy mountains",
            "hiking coloring pages",
            "alpine scenery coloring",
            "stress relief nature coloring",
            "peak landscape coloring book",
        ],
        "query": "mountains landscape bold easy coloring book",
        "cover_rgb": ((220, 235, 240), (50, 80, 100)),
        "cover_accent": (255, 200, 120),
        "back_label": "Reach the summit",
        "gradient": ((200, 225, 235), (50, 80, 105)),
        "scenes": [
            "snowy mountain peaks with pine forest and rising sun",
            "alpine lake reflecting mountains and a canoe",
            "hiking trail switchbacks with backpacker silhouette cute",
            "mountain cabin with chimney smoke and snow",
            "waterfall cascading from cliff into a pool",
            "mountain goats on a rocky ridge",
            "hot air balloon over mountain valleys",
            "ski chalet and ski lift chairs simple",
            "desert mountains with cactus and mesa",
            "volcano with gentle smoke puff and tropical plants",
            "mountain tunnel train emerging from rock",
            "campfire under mountain stars and tent",
            "rope bridge between two mountain cliffs",
            "eagle soaring over jagged peaks",
            "spring mountain meadow with wildflowers and peaks",
            "autumn aspen grove below rocky mountains",
            "mountain village with chalets and church steeple blank",
            "glacier tongue and icy blue cave entrance outlines",
            "mountain bike trail through pine woods to vista",
            "sunrise alpenglow on three pointed peaks",
            "mountain river rapids with rocks and pines",
            "lookout tower on a summit with binocular viewer",
            "mountain goats and marmot near wildflowers",
            "foggy mountain ridge with silhouettes of trees",
            "mountain pass road with hairpin turns and car",
            "cliffside monastery or temple simple bold",
            "mountain lake pier with Adirondack chairs",
            "avalanche barrier snow fences and peaks",
            "mountain wildflower alpine garden close scene with peaks behind",
            "cable car gondola over snowy slopes",
            "mountain storm clouds dramatic but simple outlines",
            "twin peaks with a rainbow between them",
            "mountain observatory under night sky",
            "hiker resting on a summit rock with map as blank rectangle",
            "mountain waterfall mill cabin scene",
            "rocky desert canyon mountains layered",
            "mountain zoo or reserve with deer in meadow peaks behind",
            "snowshoe trail through winter pines to peak view",
            "mountain vineyard terraces on hillsides",
            "full moon rising behind a single iconic peak",
        ],
    },
    "fantasy-40": {
        "prefix": "fan",
        "out_prefix": "fan",
        "title": "Fantasy",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Dragons, castles, unicorns, and cozy magic in big bold outlines.",
        "keywords": [
            "fantasy coloring book",
            "bold and easy dragons",
            "castle coloring pages",
            "unicorn coloring book",
            "simple fantasy designs",
            "stress relief coloring fantasy",
            "magic coloring book easy",
        ],
        "query": "fantasy dragons castles bold easy coloring book",
        "cover_rgb": ((245, 220, 200), (120, 50, 40)),
        "cover_accent": (255, 190, 80),
        "back_label": "Enter the realm",
        "gradient": ((245, 210, 180), (140, 55, 45)),
        "scenes": [
            "dragon sleeping on a flower hill with castle behind",
            "unicorn in a wildflower meadow under the sun",
            "stone castle with five towers and a cobble path",
            "wizard tower on a cliff above the sea",
            "mushroom fairy village with round doors",
            "cute griffin perched on ruined stones",
            "mermaid on a rock with sea stacks",
            "phoenix in a blossoming tree",
            "knight on a round horse approaching a castle gate",
            "crystal cave with a treasure chest",
            "pegasus over rolling hills",
            "elf treehouse village in a giant oak",
            "friendly troll under a stone bridge",
            "dragon egg nest on a mountain ledge",
            "floating islands with waterfalls",
            "enchanted well in a mossy grove",
            "potion still life cauldron bottles no labels",
            "castle courtyard fountain and banners as blank flags",
            "baby dragon in a flower garden",
            "unicorn and fawn by a forest stream",
            "wizard study with blank books and a round window",
            "hot air balloon over a fantasy valley",
            "sea dragon looping around a lighthouse",
            "fairy ring of mushrooms at twilight moon",
            "castle in the clouds with a long staircase",
            "centaur in an orchard",
            "magic lamp and flying carpet over dunes",
            "dwarf mine cart at a crystal tunnel",
            "swan boat on a castle moat",
            "dragon flying past a full moon",
            "cottage of a hedge witch with herbs and cats",
            "two unicorns under a rainbow",
            "knight camp with tent and round shield blank",
            "underwater palace with a mermaid garden",
            "giant friendly frog king on a lily pad throne",
            "clockwork owl on a wizard balcony",
            "harvest festival pumpkin patch with a tiny dragon",
            "ice palace with snow dragons",
            "library tree with spiral stairs no lettering",
            "sunrise over a fantasy harbor with a griffin",
        ],
    },
    "dresses-40": {
        "prefix": "drs",
        "out_prefix": "drs",
        "title": "Princess Dresses",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Ballgowns, gardens, and castle days in big bold easy outlines.",
        "keywords": [
            "princess dresses coloring book",
            "ballgown coloring pages",
            "bold and easy princess",
            "dress coloring book kids",
            "gown coloring pages",
            "stress relief fashion coloring",
            "simple princess designs",
        ],
        "query": "princess dresses bold easy coloring book",
        "cover_rgb": ((255, 230, 240), (160, 70, 110)),
        "cover_accent": (255, 200, 140),
        "back_label": "Twirl and color",
        "gradient": ((255, 220, 230), (150, 60, 100)),
        "scenes": [
            "ballgown in a rose garden courtyard",
            "princess on a balcony at sunset",
            "winter cape gown in snowy pines",
            "flower petal dress in a meadow",
            "tea-length dress at a garden tea table",
            "mermaid-silhouette gown by a fountain",
            "starry night gown under a moon",
            "riding habit beside a round horse",
            "layered ruffle gown in a ballroom with drapes",
            "simple white garden gown with a flower crown",
            "cloak and gown on a castle stair",
            "picnic dress on a checkered blanket",
            "ice-blue gown on a frozen lake shore",
            "autumn leaf gown in a pumpkin garden",
            "peacock-train gown in a courtyard",
            "dressmaker dummy with a big skirt in a sewing nook",
            "princess in a carriage with a round window",
            "gown with a long veil in a chapel garden no text",
            "seashell gown on a beach",
            "sunflower dress in a field",
            "ballet-length dress at a practice barre",
            "gown among hanging lanterns as plain globes",
            "tiny princess and a huge gown on a stand",
            "twin gowns hanging in an arched wardrobe",
            "gown on a swing under a blossoming tree",
            "masquerade gown with a simple mask shape",
            "rainy day cloak and boots under an umbrella",
            "sleepover robe and slippers in a tower room",
            "gown at a wishing well",
            "crown and gown at a vanity with a round mirror",
            "garden party dress among topiary",
            "gown on a boat in a castle moat",
            "winter ballgown with a muff and snowflakes",
            "butterfly-wing dress in a meadow",
            "gown in a greenhouse of round planters",
            "princess waving from a castle window in a gown",
            "gown beside a spinning wheel blank of text",
            "layered tulle gown on palace steps",
            "gown and a friendly dragon in a courtyard",
            "sunrise balcony gown with birds",
        ],
    },
    "cryptids-40": {
        "prefix": "cry",
        "out_prefix": "cry",
        "title": "Cryptids",
        "subtitle": "40 North American Legends to Color",
        "one_liner": "Bigfoot, Mothman, and forest legends in big bold easy outlines.",
        "keywords": [
            "cryptids coloring book",
            "bigfoot coloring pages",
            "mothman coloring book",
            "bold and easy cryptids",
            "north american legends coloring",
            "simple monster coloring cute",
            "folklore coloring book",
        ],
        "query": "bigfoot mothman cryptids bold easy coloring book",
        "cover_rgb": ((210, 230, 210), (50, 80, 55)),
        "cover_accent": (255, 200, 110),
        "back_label": "Track the legend",
        "gradient": ((190, 220, 195), (45, 85, 55)),
        "scenes": [
            "bigfoot waving from a pine forest creek",
            "mothman on a simple suspension bridge at dusk",
            "jersey devil among pines on a hill",
            "champ the lake monster in a mountain lake",
            "thunderbird soaring over mesas",
            "jackalope in a desert cactus garden",
            "hodag in a north woods clearing",
            "skunk ape in a cypress swamp",
            "ogopogo in a long lake with hills",
            "flatwoods visitor as a cute round figure in woods",
            "loveland frog on a riverbank",
            "fresno nightcrawlers on a suburban lawn cute",
            "wampus cat on a cabin porch",
            "cadborosaurus in a coastal bay",
            "dover demon as a cute big-eyed figure on a stone wall",
            "bear lake monster with a picnic shore",
            "white thing or white bigfoot on a snowy ridge",
            "honey island swamp monster in bayou boats",
            "minnesota icesnake as cute lake coils",
            "sidehill gouger on a tilted meadow",
            "splintercat in a logging clearing cute",
            "snallygaster flying over a barn",
            "lake creature at a wooden dock",
            "wood booger in appalachian laurels",
            "cactus cat in the desert night moon",
            "goatman as a cute figure on a back road",
            "momo missouri monster by a river",
            "altamaha-ha in a georgia river bend",
            "chessie the chesapeake creature by a lighthouse",
            "bessie lake erie monster with a sailboat",
            "tahoe tessie in a mountain lake",
            "bigfoot family roasting marshmallows cute",
            "mothman and a train trestle moon scene",
            "jackalope ranch with a barn",
            "thunderbird nest on a cliff",
            "champ under a stone bridge",
            "skunk ape and a cabin airboat dock",
            "hodag and a logging truck cute rounded",
            "jersey devil over a lighthouse pines",
            "bigfoot peeking from behind a giant sequoia",
        ],
    },
    "yokai-40": {
        "prefix": "yk",
        "out_prefix": "yk",
        "title": "Yokai",
        "subtitle": "40 Japanese Folklore Friends to Color",
        "one_liner": "Kitsune, kappa, and cozy yokai in big bold easy outlines.",
        "keywords": [
            "yokai coloring book",
            "kitsune coloring pages",
            "japanese folklore coloring",
            "bold and easy yokai",
            "kappa tanuki coloring",
            "cute yokai coloring book",
            "folklore creatures coloring",
        ],
        "query": "yokai kitsune kappa bold easy coloring book",
        "cover_rgb": ((255, 230, 210), (140, 50, 40)),
        "cover_accent": (255, 200, 90),
        "back_label": "Follow the foxfire",
        "gradient": ((250, 210, 180), (150, 45, 40)),
        "scenes": [
            "kitsune under shrine gates and maple trees",
            "kappa sitting by a river with a cucumber",
            "tanuki with a leaf hat in a tea garden",
            "tengu on a mountain cedar",
            "kodama tree spirits as cute orbs in an old cedar",
            "karakasa umbrella friend hopping in the rain",
            "bake-neko cat on a rooftop moon",
            "friendly oni with a peach in a mountain spring",
            "yuki-onna as a gentle winter figure among snow pines",
            "tsuchinoko on a sunny path",
            "namazu giant catfish under waves and a shrine",
            "komainu pair at a shrine stair",
            "hitodama will-o-wisps in a bamboo grove",
            "jorogumo as a cute spider-person by a web gate",
            "nurikabe as a friendly wall with a round face on a path",
            "zashiki-warashi child spirit in a cozy room",
            "bakeneko knocking a teapot in a kitchen",
            "fox wedding procession under round lanterns no text",
            "kappa swimming in a lily pond",
            "tengu flying over a torii ridge",
            "tanuki teapot still life in a forest clearing",
            "nekomata two-tailed cat on a stone lantern",
            "shojo as a gentle sea spirit on rocks",
            "amu no fuchi waterfall with a dragon-like yokai cute",
            "kitsune shrine attendant sweeping leaves",
            "umbrella yokai and rain frogs",
            "snow yokai building a snow rabbit",
            "tanuki belly drum under a full moon",
            "kappa cucumber farm by a mill wheel",
            "foxfire orbs over a wooden bridge",
            "oni hot spring with steam and towels blank",
            "bamboo princess moon scene no text",
            "stone frog yokai by a chozuya basin",
            "crane wife as a crane and a cottage",
            "moon rabbit pounding as a cute mortar scene",
            "inari foxes with blank rice-bale shapes",
            "sea kappa and a fishing boat",
            "mountain tengu nest with chicks",
            "lantern yokai as a round paper lamp with a smile",
            "maple-viewing picnic with kitsune and tanuki",
        ],
    },
    "world-cryptids-40": {
        "prefix": "wcr",
        "out_prefix": "wcr",
        "title": "World Cryptids",
        "subtitle": "40 Legends from Around the Globe",
        "one_liner": "Nessie, yeti, bunyip, and global legends in big bold easy outlines.",
        "keywords": [
            "world cryptids coloring book",
            "loch ness coloring pages",
            "yeti coloring book",
            "bunyip coloring",
            "bold and easy folklore",
            "global legends coloring",
            "chupacabra cute coloring",
        ],
        "query": "loch ness yeti bunyip cryptids coloring book",
        "cover_rgb": ((200, 225, 235), (40, 80, 110)),
        "cover_accent": (255, 200, 110),
        "back_label": "Sail the loch",
        "gradient": ((180, 215, 230), (36, 78, 112)),
        "scenes": [
            "nessie in a highland loch with a castle shore",
            "yeti on a snowy peak with prayer-flag shapes blank",
            "bunyip in an australian billabong with eucalyptus",
            "chupacabra as a cute desert creature by cacti",
            "kraken looping around a round sailing ship cute",
            "kelpie as a water horse by a scottish loch",
            "selkie on a rocky beach with a sealskin cloak",
            "yowie in australian bush",
            "mokele-mbembe in a jungle river",
            "mapinguari in amazon trees",
            "ahool giant bat over a waterfall",
            "drop bear as a cute koala-like in a gum tree",
            "wolpertinger in an alpine meadow",
            "elwetritsch in a german vineyard",
            "tatzelwurm on a rocky alpine path",
            "beast of bodmin as a big cat on moorland",
            "min-min lights as orbs over australian outback",
            "tarasque as a cute dragon-turtle in a french village",
            "bunyip and a pelican at sunset water",
            "yeti having tea outside an ice cave",
            "nessie under a stone bridge with a rowboat",
            "chupacabra and goats as cute farm friends",
            "kraken and a lighthouse island",
            "kelpie and a mill pond",
            "selkie family on tide pools",
            "yowie campfire with a swag tent",
            "jungle sauropod cryptid in a misty clearing",
            "mapinguari and a river canoe",
            "ahool cave with fruit bats cute",
            "alpine wolpertinger cottage",
            "loch ness castle ruin picnic",
            "himalayan yeti and mountain goats",
            "bunyip lily-pad lounge",
            "patagonian lake monster with andes",
            "dingonek in an african river",
            "kongamato as a cute river flyer",
            "emela-ntouka as a round jungle rhino-like friend",
            "tatzelwurm cottage garden",
            "scottish kelpie rainbow loch",
            "nessie family of three humps at dawn",
        ],
    },
    "construction-40": {
        "prefix": "con",
        "out_prefix": "con",
        "title": "Construction",
        "subtitle": "40 Bold & Easy Designs to Color",
        "one_liner": "Diggers, dump trucks, and busy sites in big bold easy outlines.",
        "keywords": [
            "construction coloring book",
            "excavator coloring pages",
            "dump truck coloring",
            "bold and easy vehicles",
            "kids construction trucks",
            "digger coloring book",
            "building site coloring",
        ],
        "query": "construction trucks excavator bold easy coloring book",
        "cover_rgb": ((255, 230, 180), (200, 140, 40)),
        "cover_accent": (255, 190, 60),
        "back_label": "Dig in and build",
        "gradient": ((255, 220, 160), (180, 110, 35)),
        "scenes": [
            "excavator digging beside a cottage frame",
            "dump truck on a dirt hill",
            "tower crane over a steel frame",
            "bulldozer pushing earth",
            "cement mixer at a house slab",
            "road roller on a new street",
            "skid steer with a pallet",
            "dump truck convoy on a site road",
            "cherry picker beside a tall lamp",
            "forklift in a lumber yard",
            "steam shovel at a quarry",
            "workers with wheelbarrows building a garden wall",
            "house framing with a cute round sawhorse",
            "dump truck filling a hopper",
            "crane lifting a beam onto a barn",
            "paver laying a road with cones as triangles",
            "backhoe at a pipe trench",
            "site trailer office as a simple hut no text",
            "kids sandbox excavator play",
            "dump truck at a beach building a sandcastle",
            "wrecking ball as a round ball on a crane cute",
            "tunnel crew with a round tunnel bore cute",
            "concrete pump arm at a high wall",
            "grader on a dirt airstrip",
            "dump truck and excavator team",
            "bridge builders with a crane over a river",
            "wind turbine install with a tall crane",
            "railroad tie crew with a small loader",
            "barn raising with a crane and ropes",
            "playground being built with a mini dumper",
            "quarry dump truck and a round boulder",
            "night site with simple floodlight globes",
            "snowplow construction loader in winter",
            "harbor crane unloading a barge",
            "pipeline crew in rolling hills",
            "tree-planting loader in a new park",
            "bricklayers on a cottage with a mixer",
            "dump truck washing station with soapy bubbles",
            "two excavators high-five buckets cute",
            "finished cottage with a tiny leftover dump truck",
        ],
    },
}

from theme_scenes_trends import TREND_THEMES  # noqa: E402

THEMES.update(TREND_THEMES)
