import type { ReelContent, Theme, ThemeId } from "./types";

export const THEMES: Record<ThemeId, Theme> = {
  cosmic: {
    id: "cosmic",
    name: "Cosmic",
    bg: "#13071B",
    blobs: [
      { color: "rgba(118, 28, 96, 0.55)", x: 0.28, y: 0.18, r: 0.62 },
      { color: "rgba(58, 12, 78, 0.62)", x: 0.78, y: 0.12, r: 0.5 },
      { color: "rgba(86, 18, 110, 0.48)", x: 0.55, y: 0.55, r: 0.7 },
      { color: "rgba(42, 8, 64, 0.7)", x: 0.18, y: 0.82, r: 0.58 },
      { color: "rgba(150, 42, 92, 0.32)", x: 0.82, y: 0.78, r: 0.52 },
      { color: "rgba(28, 6, 48, 0.55)", x: 0.5, y: 0.92, r: 0.46 },
    ],
    accent: "#54E86B",
    text: "#F7F2F8",
    mute: "rgba(247, 242, 248, 0.42)",
    star: "rgba(255, 210, 255, 0.55)",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    bg: "#04121C",
    blobs: [
      { color: "rgba(12, 70, 92, 0.6)", x: 0.3, y: 0.2, r: 0.6 },
      { color: "rgba(8, 40, 80, 0.55)", x: 0.75, y: 0.35, r: 0.5 },
      { color: "rgba(20, 90, 110, 0.4)", x: 0.5, y: 0.75, r: 0.65 },
      { color: "rgba(6, 30, 50, 0.7)", x: 0.15, y: 0.85, r: 0.5 },
    ],
    accent: "#5EE0C8",
    text: "#F2FBFF",
    mute: "rgba(242, 251, 255, 0.42)",
    star: "rgba(180, 240, 255, 0.5)",
  },
  ember: {
    id: "ember",
    name: "Ember",
    bg: "#16080A",
    blobs: [
      { color: "rgba(120, 36, 24, 0.5)", x: 0.3, y: 0.22, r: 0.58 },
      { color: "rgba(80, 18, 30, 0.55)", x: 0.78, y: 0.18, r: 0.48 },
      { color: "rgba(90, 30, 18, 0.4)", x: 0.55, y: 0.7, r: 0.6 },
      { color: "rgba(40, 10, 12, 0.7)", x: 0.2, y: 0.88, r: 0.5 },
    ],
    accent: "#FFB25A",
    text: "#FFF6EE",
    mute: "rgba(255, 246, 238, 0.42)",
    star: "rgba(255, 210, 160, 0.5)",
  },
};

export const TEMPLATES: ReelContent[] = [
  {
    id: "apartheid",
    name: "Apartheid 1994",
    episode: "30",
    title: "The End of Apartheid",
    year: "1994",
    imageUrl: "/images/mandela-voting-1994.jpg",
    imageCaption: "Nelson Mandela voting, 1994",
    imageCredit: "Photo: Paul Weinberg, 1994 · CC BY-SA 3.0",
    bullets: [
      "Apartheid was South Africa’s legal system of racial segregation (1948–1994)",
      "Nelson Mandela spent 27 years in prison for anti-apartheid activism",
      "International boycotts and sanctions pressured the white minority government",
      "Mandela was released in 1990 and negotiated a peaceful transition",
      "First democratic elections held April 27, 1994 — Mandela became president",
      "At age 75, he chose reconciliation over revenge",
      "The Truth and Reconciliation Commission addressed past atrocities",
      "South Africa’s transition is studied as a model of peaceful revolution",
      "The African National Congress won that first open vote after decades banned",
      "A 1996 constitution locked in equal rights after apartheid collapsed",
      "Mandela and F. W. de Klerk shared the 1993 Nobel Peace Prize for the talks",
      "Black South Africans had been denied a national vote until those 1994 elections",
    ],
    hashtags: "#NelsonMandela #Apartheid #SouthAfrica #HistoryTok",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "dolly",
    name: "Dolly Parton",
    episode: "396",
    title: "Dolly Parton",
    year: "1973",
    imageUrl: "/images/dolly-parton-2010.jpg",
    imageCaption: "Dolly Parton, Liseberg Applause Award, 2010",
    imageCredit: "Photo: Curtis Hilbun, 2010 · CC BY 3.0",
    bullets: [
      "Dolly Parton was born January 19, 1946, in Sevier County, Tennessee, the fourth of twelve children",
      "She joined the Grand Ole Opry in 1969 at age twenty-two",
      "She wrote “Coat of Many Colors” about a coat her mother sewed from rags",
      "She wrote “Jolene” and “I Will Always Love You” in the same 1973 writing streak",
      "Elvis wanted “I Will Always Love You” if she gave up half the publishing — she said no",
      "Her song “9 to 5” named the 1980 comedy and later topped the Billboard Hot 100",
      "She opened Dollywood in Pigeon Forge, Tennessee, in 1986",
      "She earned the Kennedy Center Honors in 2006",
      "Her Imagination Library has mailed more than 200 million free books to children",
      "In 2020 she gave Vanderbilt $1 million toward COVID-19 vaccine research",
      "She was inducted into the Rock & Roll Hall of Fame in 2022",
      "She has written more than 3,000 songs and sold more than 100 million records",
    ],
    hashtags:
      "#DollyParton #Jolene #IWillAlwaysLoveYou #CountryMusic #MusicHistory #HistoryTok #DidYouKnow #FactsOrWhacks",
    postCaption: [
      "She wrote “Jolene” and “I Will Always Love You” in the same writing streak.",
      "",
      "Elvis wanted half the publishing. She said no. Whitney still made it a global anthem.",
      "",
      "Then she built a theme park, mailed 200 million free books, and dropped a million on COVID vaccine research.",
      "",
      "The blueprint. Since 1946.",
      "",
      "@FactsOrWhacks",
      "#DollyParton #Jolene #IWillAlwaysLoveYou #CountryMusic #MusicHistory #HistoryTok #DidYouKnow #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ember",
    reveal: "hold",
  },
  {
    id: "tim-curry",
    name: "Tim Curry",
    episode: "397",
    title: "Tim Curry",
    year: "1946–2026",
    imageUrl: "/images/tim-curry-2025.jpg",
    imageCaption: "Tim Curry, Rocky Horror 50th anniversary, 2025",
    imageCredit: "Photo: Kevin Paul, 2025 · CC BY 4.0",
    bullets: [
      "Timothy James Curry was born April 19, 1946, in Grappenhall, Cheshire, England",
      "He broke through in London’s original 1968 production of Hair",
      "Richard O’Brien wrote Dr. Frank-N-Furter after they met during Hair",
      "The Rocky Horror Picture Show in 1975 made him a midnight-movie cult icon",
      "He earned a Tony nomination as Mozart in Amadeus on Broadway in 1980",
      "In 1985 he played Darkness in Legend and Wadsworth the butler in Clue",
      "He terrified a generation as Pennywise in the 1990 miniseries of It",
      "He won a Daytime Emmy as Captain Hook in Peter Pan and the Pirates",
      "He voiced Sir Nigel Thornberry and later Darth Sidious in The Clone Wars",
      "He earned three Tony nominations, including King Arthur in Spamalot",
      "After a 2012 stroke he kept working, and published his memoir Vagabond in 2025",
      "He died at his Los Angeles home on August 25, 2026, at age 80",
    ],
    hashtags:
      "#TimCurry #RockyHorror #RipTimCurry #Pennywise #Clue #MovieTok #HistoryTok #FactsOrWhacks",
    postCaption: [
      "He turned a midnight movie into a 50-year party.",
      "",
      "Frank-N-Furter. Pennywise. Wadsworth. Nigel Thornberry. Same voice. Zero repeats.",
      "",
      "Tim Curry, 1946–2026. The villain era lasted five decades.",
      "",
      "@FactsOrWhacks",
      "#TimCurry #RockyHorror #RipTimCurry #Pennywise #Clue #MovieTok #HistoryTok #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "peter-cullen",
    name: "Peter Cullen",
    episode: "398",
    title: "Peter Cullen",
    year: "1941–2026",
    imageUrl: "/images/peter-cullen-2023.jpg",
    imageCaption: "Peter Cullen, GalaxyCon Columbus, 2023",
    imageCredit: "Photo: Pedro Heshike, 2023 · CC BY 2.0",
    bullets: [
      "Peter Claver Cullen was born July 28, 1941, in Montreal, Quebec",
      "He was in the first graduating class of the National Theatre School of Canada in 1963",
      "He announced The Smothers Brothers Comedy Hour and appeared on The Sonny & Cher Comedy Hour",
      "He based Optimus Prime’s voice on his brother Larry, a Marine who served in Vietnam",
      "Larry’s advice: real heroes don’t yell — they are tough enough to be gentle",
      "He originated Optimus Prime and Ironhide on The Transformers in 1984",
      "Kids were so upset when Optimus died in the 1986 movie that the studio brought him back",
      "He returned as Optimus for the 2007 live-action film and kept the role through Rise of the Beasts",
      "He voiced Eeyore in Disney’s Winnie the Pooh films and series",
      "He was the first Western voice of Mario, on Saturday Supercade in 1983",
      "Hasbro put him in the Transformers Hall of Fame; in 2023 he received a Children’s & Family Emmy Lifetime Achievement Award",
      "He died on August 26, 2026, at age 85",
    ],
    hashtags:
      "#PeterCullen #OptimusPrime #Transformers #RipPeterCullen #Eeyore #VoiceActing #HistoryTok #FactsOrWhacks",
    postCaption: [
      "He based Optimus Prime on his brother the Marine: tough enough to be gentle.",
      "",
      "Then he led Autobots for forty years, voiced Eeyore, and became the West’s first Mario.",
      "",
      "Peter Cullen, 1941–2026. The quiet hero in a thousand living rooms.",
      "",
      "@FactsOrWhacks",
      "#PeterCullen #OptimusPrime #Transformers #RipPeterCullen #Eeyore #VoiceActing #HistoryTok #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ocean",
    reveal: "hold",
  },
  {
    id: "hayden-panettiere",
    name: "Hayden Panettiere",
    episode: "399",
    title: "Hayden Panettiere",
    year: "1989–2026",
    imageUrl: "/images/hayden-panettiere-2011.jpg",
    imageCaption: "Hayden Panettiere, Fan Expo Toronto, 2011",
    imageCredit: "Photo: Tabercil, 2011 · CC BY-SA 2.0",
    bullets: [
      "Hayden Panettiere was born August 21, 1989, in Palisades, New York",
      "She acted as a child, including Sheryl Yoast in Remember the Titans in 2000",
      "In 2006 she became Claire Bennet on Heroes, a cheerleader who could heal from anything",
      "Heroes made her a global teen star and ran through 2010",
      "On ABC’s Nashville she played Juliette Barnes, a country star as sharp as she was wounded",
      "Juliette earned her two Golden Globe nominations for Best Supporting Actress",
      "In Scream 4 she played Kirby Reed, then returned as Kirby in Scream VI",
      "She also voiced Kairi in the Kingdom Hearts games",
      "In 2007 she paddled into Taiji’s cove to protest the dolphin hunt, a scene later shown in The Cove",
      "She and heavyweight champion Wladimir Klitschko had a daughter, Kaya, in 2014",
      "In May 2026 she published This Is Me: A Reckoning, writing openly about fame and mental health",
      "She died on August 16, 2026, in Greenville, South Carolina, at age 36",
    ],
    hashtags:
      "#HaydenPanettiere #Heroes #Nashville #Scream #RipHaydenPanettiere #MovieTok #HistoryTok #FactsOrWhacks",
    postCaption: [
      "She made cheerleaders superheroes and country stars complicated.",
      "",
      "Claire Bennet. Juliette Barnes. Kirby Reed. Same fire.",
      "",
      "Hayden Panettiere, 1989–2026. Thirty-six years was not enough.",
      "",
      "@FactsOrWhacks",
      "#HaydenPanettiere #Heroes #Nashville #Scream #RipHaydenPanettiere #MovieTok #HistoryTok #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "btk",
    name: "BTK",
    episode: "400",
    title: "BTK",
    year: "1974–2005",
    imageUrl: "/images/dennis-rader-airman.jpg",
    imageCaption: "Dennis Rader, U.S. Air Force, 1966",
    imageCredit: "Photo: U.S. Air Force, 1966 · Public domain",
    bullets: [
      "Dennis Lynn Rader was born March 9, 1945, in Pittsburg, Kansas",
      "He named himself BTK — bind, torture, kill — in letters to police and the press",
      "His first known murders were four members of the Otero family in Wichita on January 15, 1974",
      "Investigators later tied him to ten murders in the Wichita area between 1974 and 1991",
      "From 1974 to 1988 he installed ADT home alarms in the same city he was terrorizing",
      "After 1991 he went silent for more than a decade, then mailed new taunts in 2004",
      "Neighbors knew him as Park City’s compliance officer and dogcatcher",
      "He was president of Christ Lutheran Church’s council and a Cub Scout leader",
      "He asked if a floppy disk could be traced; police ran a newspaper ad saying it would be ok",
      "A disk he sent in 2005 still held metadata: Christ Lutheran Church, last saved by Dennis",
      "Police arrested him in Park City on February 25, 2005",
      "He pleaded guilty to ten murders and was sentenced to ten consecutive life terms, 175 years",
    ],
    hashtags:
      "#BTK #DennisRader #TrueCrime #TrueCrimeTok #HistoryTok #DidYouKnow #FactsOrWhacks",
    postCaption: [
      "Church president. Cub Scout leader. City inspector.",
      "",
      "Also BTK.",
      "",
      "He asked if a floppy disk could be traced. Police ran an ad: it would be ok.",
      "The leftover metadata said Dennis.",
      "",
      "The cases they skip in class. Follow @FactsOrWhacks.",
      "",
      "#BTK #DennisRader #TrueCrime #TrueCrimeTok #HistoryTok #DidYouKnow #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ember",
    reveal: "hold",
  },
  {
    id: "katrina",
    name: "Hurricane Katrina",
    episode: "401",
    title: "Hurricane Katrina",
    year: "2005",
    imageUrl: "/images/katrina-new-orleans-2005.jpg",
    imageCaption: "New Orleans after Katrina, looking toward Lake Pontchartrain, 2005",
    imageCredit: "Photo: Kyle Niemi / U.S. Coast Guard, 2005 · Public domain",
    bullets: [
      "Hurricane Katrina made landfall near Buras, Louisiana, at 6:10 a.m. on August 29, 2005",
      "It had peaked as a Category 5 over the Gulf, then came ashore as a Category 3",
      "The storm surge along the Mississippi coast reached about 24 to 28 feet",
      "New Orleans’s federally built levees failed in more than 50 places",
      "Within 48 hours, about 80 percent of New Orleans was underwater",
      "Industrial Canal breaches put the Lower Ninth Ward under more than 10 feet of water",
      "The National Hurricane Center later counted 1,392 deaths tied to Katrina",
      "It remains the costliest hurricane in U.S. history, with damage later estimated near $190 billion",
      "More than a million people were displaced, the largest U.S. movement since the Dust Bowl",
      "Tens of thousands waited at the Superdome and Convention Center as rescue lagged",
      "Investigators later found the levee system, not just the wind, caused the city’s flooding",
      "The name Katrina was retired, and New Orleans still marks the date every August 29",
    ],
    hashtags:
      "#HurricaneKatrina #Katrina #NewOrleans #OnThisDay #HistoryTok #DidYouKnow #FactsOrWhacks",
    postCaption: [
      "The hurricane didn’t drown New Orleans.",
      "",
      "The levees did.",
      "",
      "Category 5 in the Gulf. Category 3 at landfall. 80% of the city underwater.",
      "",
      "21 years ago today. Follow @FactsOrWhacks for the days they still argue about.",
      "",
      "#HurricaneKatrina #Katrina #NewOrleans #OnThisDay #HistoryTok #DidYouKnow #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ocean",
    reveal: "hold",
  },
  {
    id: "thurgood-marshall",
    name: "Thurgood Marshall",
    episode: "402",
    title: "Thurgood Marshall",
    year: "1967",
    imageUrl: "/images/thurgood-marshall-1967.jpg",
    imageCaption: "Thurgood Marshall, White House, 1967",
    imageCredit: "Photo: Yoichi Okamoto, 1967 · Public domain",
    bullets: [
      "Thoroughgood “Thurgood” Marshall was born July 2, 1908, in Baltimore, Maryland",
      "The University of Maryland Law School rejected him because he was Black",
      "He graduated first in his class from Howard University Law School in 1933",
      "At Howard he trained under Charles Hamilton Houston to use the courts against Jim Crow",
      "In 1935 he helped win Murray v. Pearson, opening Maryland’s law school to Black students",
      "As NAACP Legal Defense Fund chief he argued 32 Supreme Court cases and won 29",
      "In 1954 he won Brown v. Board of Education, ending legal segregation in public schools",
      "President Kennedy named him to the Second Circuit in 1961; Johnson made him the first Black solicitor general in 1965",
      "Johnson nominated him to the Supreme Court on June 13, 1967, to succeed Tom C. Clark",
      "He served nearly 24 years, often dissenting as the Court turned more conservative",
      "He retired in 1991 and died January 24, 1993; he is buried at Arlington National Cemetery",
      "On August 30, 1967, the Senate confirmed him 69–11 as the first Black justice",
    ],
    hashtags:
      "#ThurgoodMarshall #SCOTUS #OnThisDay #BlackHistory #HistoryTok #DidYouKnow #FactsOrWhacks",
    postCaption: [
      "He wasn’t allowed into Maryland’s law school.",
      "",
      "So he sued. Then he desegregated America’s schools.",
      "",
      "Then, 59 years ago today, the Senate put him on the Supreme Court.",
      "",
      "Thurgood Marshall. First Black justice. Follow @FactsOrWhacks.",
      "",
      "#ThurgoodMarshall #SCOTUS #OnThisDay #BlackHistory #HistoryTok #DidYouKnow #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ember",
    reveal: "hold",
  },
  {
    id: "princess-diana",
    name: "Princess Diana",
    episode: "403",
    title: "Princess Diana",
    year: "1961–1997",
    imageUrl: "/images/princess-diana-1985.jpg",
    imageCaption: "Diana, Princess of Wales, White House, 1985",
    imageCredit: "Photo: White House, 1985 · Public domain",
    bullets: [
      "Diana Frances Spencer was born July 1, 1961, at Park House on the Sandringham estate",
      "She married Prince Charles at St Paul’s Cathedral on July 29, 1981, with about 750 million watching",
      "Their sons William and Harry were born in 1982 and 1984",
      "In 1987 she shook hands without gloves in a London AIDS ward, helping kill the myth that HIV spread by touch",
      "In January 1997 she walked a cleared minefield in Angola to push a global landmine ban",
      "In a 1995 BBC Panorama interview she said, “there were three of us in this marriage”",
      "She and Charles divorced on August 28, 1996, and she lost the style Her Royal Highness",
      "After the divorce she kept the title Diana, Princess of Wales",
      "After midnight on August 31, 1997, a Mercedes left the Ritz Paris to dodge paparazzi and crashed in the Pont de l’Alma tunnel",
      "Driver Henri Paul was more than three times France’s legal alcohol limit; nobody in the car wore a seat belt",
      "A 2008 British inquest returned a verdict of unlawful killing, citing the driver and the pursuing paparazzi",
      "She died at 4 a.m. at Pitié-Salpêtrière Hospital on August 31, 1997; she was 36",
    ],
    hashtags:
      "#PrincessDiana #Diana #OnThisDay #RoyalFamily #HistoryTok #DidYouKnow #FactsOrWhacks",
    postCaption: [
      "29 years ago tonight, the most famous woman on earth died in a Paris tunnel.",
      "",
      "The driver was drunk. Nobody wore a seat belt. The paparazzi were chasing.",
      "",
      "Diana. 36 years old. Follow @FactsOrWhacks.",
      "",
      "#PrincessDiana #Diana #OnThisDay #RoyalFamily #HistoryTok #DidYouKnow #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "universe",
    name: "Observable universe",
    episode: "12",
    title: "The Observable Universe",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "The universe is about 13.8 billion years old, dating from the Big Bang",
      "The observable universe spans roughly 93 billion light-years",
      "It holds on the order of 2 trillion galaxies, each packed with stars",
      "There are more stars out there than grains of sand on Earth",
      "We live on one planet, on one arm, of one galaxy among billions",
      "Light from the farthest galaxies has traveled more than 13 billion years",
      "Most of the cosmos is dark energy and dark matter we cannot see directly",
      "The cosmic microwave background is leftover glow from the Big Bang",
      "The Milky Way is one of two giant galaxies in our Local Group",
      "If the Sun were a seed, the nearest star would still sit kilometers away",
      "Distant galaxies recede faster as space itself expands",
      "Nothing we send can catch galaxies beyond the cosmic horizon",
    ],
    hashtags: "#Space #Universe #Astronomy #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "oceans",
    name: "Earth's oceans",
    episode: "18",
    title: "How Deep Earth's Oceans Go",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Water covers about 71% of Earth’s surface",
      "The average seafloor sits roughly 3.7 km down",
      "The Mariana Trench plunges about 11 km",
      "Less than 25% of the seafloor is mapped in high detail",
      "Most of Earth’s habitable space is ocean, not land",
      "The ocean holds about 97 percent of Earth’s water",
      "Pressure in the deepest trenches can exceed 1,000 atmospheres",
      "Phytoplankton produce roughly half of the oxygen we breathe",
      "Sunlight fades in the first 200 meters — most ocean is permanent night",
      "The Southern Ocean current is the largest on the planet",
      "Seawater absorbs about a quarter of human carbon dioxide emissions",
      "New species are still being found in the deep every year",
    ],
    hashtags: "#Ocean #Earth #Science #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ocean",
    reveal: "hold",
  },
  {
    id: "internet",
    name: "Internet in a day",
    episode: "7",
    title: "What the Internet Moves in a Day",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Roughly 361 billion emails are sent in a single day",
      "People run about 8.5 billion Google searches daily",
      "Hundreds of millions of hours of video are watched every day",
      "Billions of new images are uploaded across the web",
      "The day’s data traffic outweighs every book ever printed",
      "More than 5 billion people now use the internet",
      "A large data center can draw as much power as a town",
      "Undersea cables carry almost all intercontinental internet traffic",
      "Streaming video accounts for most of the web’s bandwidth",
      "The first website went live in 1991 at CERN",
      "There are now more internet-connected devices than people",
      "Spam still makes up a huge share of all email sent",
    ],
    hashtags: "#Internet #Tech #Data #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "body",
    name: "Human body",
    episode: "4",
    title: "The Strange Scale of a Human Body",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "You are about 30 trillion cells, plus at least as many microbes",
      "The heart pumps around 7,500 liters of blood a day",
      "Nerve signals can fire at up to 120 meters per second",
      "Uncoiled DNA in one body would stretch to the Sun",
      "The brain has about 86 billion neurons and uses ~20% of your energy",
      "Bones remodel continuously — you replace your skeleton over years",
      "Lungs unfurled would cover about the area of a tennis court",
      "You blink roughly 15 to 20 times a minute without thinking",
      "Gut bacteria help digest food and train the immune system",
      "Skin is the body’s largest organ",
      "Red blood cells live about 120 days before the spleen recycles them",
      "You make roughly a liter of saliva a day",
    ],
    hashtags: "#Body #Biology #Science #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ember",
    reveal: "hold",
  },
];

export function cloneTemplate(template: ReelContent): ReelContent {
  return {
    ...template,
    bullets: [...template.bullets],
  };
}

export function blankReel(): ReelContent {
  return {
    id: "custom",
    name: "Custom",
    episode: "1",
    title: "Your Headline",
    year: "2026",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Lead with one clear sentence people can read in a breath",
      "Follow with the turning point or the number that matters",
      "Keep each line to a single fact, not a paragraph",
      "Name the person, place, or year that makes it concrete",
      "Add the cause, then the effect, on separate lines",
      "Skip hashtags here — they belong on the post, not the frame",
      "Use a number when it is the point of the sentence",
      "Say what changed after the event, not only what happened",
      "Keep type large enough to read on a phone",
      "Credit the photograph so the still can travel",
      "Twelve facts fill a 9:16 reel without feeling empty",
      "End on why it still matters",
    ],
    hashtags: "#HistoryTok #FactsOrWhacks",
    handle: "@YourHandle",
    durationSec: 20,
    theme: "cosmic",
    reveal: "hold",
  };
}
