import type { ReelContent, Theme, ThemeId } from "./types";

export const THEMES: Record<ThemeId, Theme> = {
  cosmic: {
    id: "cosmic",
    name: "Cosmic",
    bg: "#13071B",
    blobs: [
      { color: "rgba(118, 28, 96, 0.55)", x: 0.28, y: 0.18, r: 0.62 },
      { color: "rgba(58, 12, 78, 0.62)", x: 0.78, y: 0.12, r: 0.5 },
      { color: "rgba(86, 18, 110, 0.48)", x: 0.55, y: 0.55, r: 0.7 },
      { color: "rgba(42, 8, 64, 0.7)", x: 0.18, y: 0.82, r: 0.58 },
      { color: "rgba(150, 42, 92, 0.32)", x: 0.82, y: 0.78, r: 0.52 },
      { color: "rgba(28, 6, 48, 0.55)", x: 0.5, y: 0.92, r: 0.46 },
    ],
    accent: "#54E86B",
    text: "#F7F2F8",
    mute: "rgba(247, 242, 248, 0.42)",
    star: "rgba(255, 210, 255, 0.55)",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    bg: "#04121C",
    blobs: [
      { color: "rgba(12, 70, 92, 0.6)", x: 0.3, y: 0.2, r: 0.6 },
      { color: "rgba(8, 40, 80, 0.55)", x: 0.75, y: 0.35, r: 0.5 },
      { color: "rgba(20, 90, 110, 0.4)", x: 0.5, y: 0.75, r: 0.65 },
      { color: "rgba(6, 30, 50, 0.7)", x: 0.15, y: 0.85, r: 0.5 },
    ],
    accent: "#5EE0C8",
    text: "#F2FBFF",
    mute: "rgba(242, 251, 255, 0.42)",
    star: "rgba(180, 240, 255, 0.5)",
  },
  ember: {
    id: "ember",
    name: "Ember",
    bg: "#16080A",
    blobs: [
      { color: "rgba(120, 36, 24, 0.5)", x: 0.3, y: 0.22, r: 0.58 },
      { color: "rgba(80, 18, 30, 0.55)", x: 0.78, y: 0.18, r: 0.48 },
      { color: "rgba(90, 30, 18, 0.4)", x: 0.55, y: 0.7, r: 0.6 },
      { color: "rgba(40, 10, 12, 0.7)", x: 0.2, y: 0.88, r: 0.5 },
    ],
    accent: "#FFB25A",
    text: "#FFF6EE",
    mute: "rgba(255, 246, 238, 0.42)",
    star: "rgba(255, 210, 160, 0.5)",
  },
};

export const TEMPLATES: ReelContent[] = [
  {
    id: "apartheid",
    name: "Apartheid 1994",
    episode: "30",
    title: "The End of Apartheid",
    year: "1994",
    imageUrl: "/images/mandela-voting-1994.jpg",
    imageCaption: "Nelson Mandela voting, 1994",
    imageCredit: "Photo: Paul Weinberg, 1994 · CC BY-SA 3.0",
    bullets: [
      "Apartheid was South Africa’s legal system of racial segregation (1948–1994)",
      "Nelson Mandela spent 27 years in prison for anti-apartheid activism",
      "International boycotts and sanctions pressured the white minority government",
      "Mandela was released in 1990 and negotiated a peaceful transition",
      "First democratic elections held April 27, 1994 — Mandela became president",
      "At age 75, he chose reconciliation over revenge",
      "The Truth and Reconciliation Commission addressed past atrocities",
      "South Africa’s transition is studied as a model of peaceful revolution",
      "The African National Congress won that first open vote after decades banned",
      "A 1996 constitution locked in equal rights after apartheid collapsed",
      "Mandela and F. W. de Klerk shared the 1993 Nobel Peace Prize for the talks",
      "Black South Africans had been denied a national vote until those 1994 elections",
    ],
    hashtags: "#NelsonMandela #Apartheid #SouthAfrica #HistoryTok",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "dolly",
    name: "Dolly Parton",
    episode: "396",
    title: "Dolly Parton",
    year: "1973",
    imageUrl: "/images/dolly-parton-2010.jpg",
    imageCaption: "Dolly Parton, Liseberg Applause Award, 2010",
    imageCredit: "Photo: Curtis Hilbun, 2010 · CC BY 3.0",
    bullets: [
      "Dolly Parton was born January 19, 1946, in Sevier County, Tennessee, the fourth of twelve children",
      "She joined the Grand Ole Opry in 1969 at age twenty-two",
      "She wrote “Coat of Many Colors” about a coat her mother sewed from rags",
      "She wrote “Jolene” and “I Will Always Love You” in the same 1973 writing streak",
      "Elvis wanted “I Will Always Love You” if she gave up half the publishing — she said no",
      "Her song “9 to 5” named the 1980 comedy and later topped the Billboard Hot 100",
      "She opened Dollywood in Pigeon Forge, Tennessee, in 1986",
      "She earned the Kennedy Center Honors in 2006",
      "Her Imagination Library has mailed more than 200 million free books to children",
      "In 2020 she gave Vanderbilt $1 million toward COVID-19 vaccine research",
      "She was inducted into the Rock & Roll Hall of Fame in 2022",
      "She has written more than 3,000 songs and sold more than 100 million records",
    ],
    hashtags:
      "#DollyParton #Jolene #IWillAlwaysLoveYou #CountryMusic #MusicHistory #HistoryTok #DidYouKnow #FactsOrWhacks",
    postCaption: [
      "She wrote “Jolene” and “I Will Always Love You” in the same writing streak.",
      "",
      "Elvis wanted half the publishing. She said no. Whitney still made it a global anthem.",
      "",
      "Then she built a theme park, mailed 200 million free books, and dropped a million on COVID vaccine research.",
      "",
      "The blueprint. Since 1946.",
      "",
      "@FactsOrWhacks",
      "#DollyParton #Jolene #IWillAlwaysLoveYou #CountryMusic #MusicHistory #HistoryTok #DidYouKnow #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ember",
    reveal: "hold",
  },
  {
    id: "tim-curry",
    name: "Tim Curry",
    episode: "397",
    title: "Tim Curry",
    year: "1946–2026",
    imageUrl: "/images/tim-curry-2025.jpg",
    imageCaption: "Tim Curry, Rocky Horror 50th anniversary, 2025",
    imageCredit: "Photo: Kevin Paul, 2025 · CC BY 4.0",
    bullets: [
      "Timothy James Curry was born April 19, 1946, in Grappenhall, Cheshire, England",
      "He broke through in London’s original 1968 production of Hair",
      "Richard O’Brien wrote Dr. Frank-N-Furter after they met during Hair",
      "The Rocky Horror Picture Show in 1975 made him a midnight-movie cult icon",
      "He earned a Tony nomination as Mozart in Amadeus on Broadway in 1980",
      "In 1985 he played Darkness in Legend and Wadsworth the butler in Clue",
      "He terrified a generation as Pennywise in the 1990 miniseries of It",
      "He won a Daytime Emmy as Captain Hook in Peter Pan and the Pirates",
      "He voiced Sir Nigel Thornberry and later Darth Sidious in The Clone Wars",
      "He earned three Tony nominations, including King Arthur in Spamalot",
      "After a 2012 stroke he kept working, and published his memoir Vagabond in 2025",
      "He died at his Los Angeles home on August 25, 2026, at age 80",
    ],
    hashtags:
      "#TimCurry #RockyHorror #RipTimCurry #Pennywise #Clue #MovieTok #HistoryTok #FactsOrWhacks",
    postCaption: [
      "He turned a midnight movie into a 50-year party.",
      "",
      "Frank-N-Furter. Pennywise. Wadsworth. Nigel Thornberry. Same voice. Zero repeats.",
      "",
      "Tim Curry, 1946–2026. The villain era lasted five decades.",
      "",
      "@FactsOrWhacks",
      "#TimCurry #RockyHorror #RipTimCurry #Pennywise #Clue #MovieTok #HistoryTok #FactsOrWhacks",
    ].join("\n"),
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "universe",
    name: "Observable universe",
    episode: "12",
    title: "The Observable Universe",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "The universe is about 13.8 billion years old, dating from the Big Bang",
      "The observable universe spans roughly 93 billion light-years",
      "It holds on the order of 2 trillion galaxies, each packed with stars",
      "There are more stars out there than grains of sand on Earth",
      "We live on one planet, on one arm, of one galaxy among billions",
      "Light from the farthest galaxies has traveled more than 13 billion years",
      "Most of the cosmos is dark energy and dark matter we cannot see directly",
      "The cosmic microwave background is leftover glow from the Big Bang",
      "The Milky Way is one of two giant galaxies in our Local Group",
      "If the Sun were a seed, the nearest star would still sit kilometers away",
      "Distant galaxies recede faster as space itself expands",
      "Nothing we send can catch galaxies beyond the cosmic horizon",
    ],
    hashtags: "#Space #Universe #Astronomy #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "oceans",
    name: "Earth's oceans",
    episode: "18",
    title: "How Deep Earth's Oceans Go",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Water covers about 71% of Earth’s surface",
      "The average seafloor sits roughly 3.7 km down",
      "The Mariana Trench plunges about 11 km",
      "Less than 25% of the seafloor is mapped in high detail",
      "Most of Earth’s habitable space is ocean, not land",
      "The ocean holds about 97 percent of Earth’s water",
      "Pressure in the deepest trenches can exceed 1,000 atmospheres",
      "Phytoplankton produce roughly half of the oxygen we breathe",
      "Sunlight fades in the first 200 meters — most ocean is permanent night",
      "The Southern Ocean current is the largest on the planet",
      "Seawater absorbs about a quarter of human carbon dioxide emissions",
      "New species are still being found in the deep every year",
    ],
    hashtags: "#Ocean #Earth #Science #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ocean",
    reveal: "hold",
  },
  {
    id: "internet",
    name: "Internet in a day",
    episode: "7",
    title: "What the Internet Moves in a Day",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Roughly 361 billion emails are sent in a single day",
      "People run about 8.5 billion Google searches daily",
      "Hundreds of millions of hours of video are watched every day",
      "Billions of new images are uploaded across the web",
      "The day’s data traffic outweighs every book ever printed",
      "More than 5 billion people now use the internet",
      "A large data center can draw as much power as a town",
      "Undersea cables carry almost all intercontinental internet traffic",
      "Streaming video accounts for most of the web’s bandwidth",
      "The first website went live in 1991 at CERN",
      "There are now more internet-connected devices than people",
      "Spam still makes up a huge share of all email sent",
    ],
    hashtags: "#Internet #Tech #Data #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "body",
    name: "Human body",
    episode: "4",
    title: "The Strange Scale of a Human Body",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "You are about 30 trillion cells, plus at least as many microbes",
      "The heart pumps around 7,500 liters of blood a day",
      "Nerve signals can fire at up to 120 meters per second",
      "Uncoiled DNA in one body would stretch to the Sun",
      "The brain has about 86 billion neurons and uses ~20% of your energy",
      "Bones remodel continuously — you replace your skeleton over years",
      "Lungs unfurled would cover about the area of a tennis court",
      "You blink roughly 15 to 20 times a minute without thinking",
      "Gut bacteria help digest food and train the immune system",
      "Skin is the body’s largest organ",
      "Red blood cells live about 120 days before the spleen recycles them",
      "You make roughly a liter of saliva a day",
    ],
    hashtags: "#Body #Biology #Science #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 24,
    theme: "ember",
    reveal: "hold",
  },
];

export function cloneTemplate(template: ReelContent): ReelContent {
  return {
    ...template,
    bullets: [...template.bullets],
  };
}

export function blankReel(): ReelContent {
  return {
    id: "custom",
    name: "Custom",
    episode: "1",
    title: "Your Headline",
    year: "2026",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Lead with one clear sentence people can read in a breath",
      "Follow with the turning point or the number that matters",
      "Keep each line to a single fact, not a paragraph",
      "Name the person, place, or year that makes it concrete",
      "Add the cause, then the effect, on separate lines",
      "Skip hashtags here — they belong on the post, not the frame",
      "Use a number when it is the point of the sentence",
      "Say what changed after the event, not only what happened",
      "Keep type large enough to read on a phone",
      "Credit the photograph so the still can travel",
      "Twelve facts fill a 9:16 reel without feeling empty",
      "End on why it still matters",
    ],
    hashtags: "#HistoryTok #FactsOrWhacks",
    handle: "@YourHandle",
    durationSec: 20,
    theme: "cosmic",
    reveal: "hold",
  };
}
