import type { ReelContent, Theme, ThemeId } from "./types";

export const THEMES: Record<ThemeId, Theme> = {
  cosmic: {
    id: "cosmic",
    name: "Cosmic",
    bg: "#13071B",
    blobs: [
      { color: "rgba(118, 28, 96, 0.55)", x: 0.28, y: 0.18, r: 0.62 },
      { color: "rgba(58, 12, 78, 0.62)", x: 0.78, y: 0.12, r: 0.5 },
      { color: "rgba(86, 18, 110, 0.48)", x: 0.55, y: 0.55, r: 0.7 },
      { color: "rgba(42, 8, 64, 0.7)", x: 0.18, y: 0.82, r: 0.58 },
      { color: "rgba(150, 42, 92, 0.32)", x: 0.82, y: 0.78, r: 0.52 },
      { color: "rgba(28, 6, 48, 0.55)", x: 0.5, y: 0.92, r: 0.46 },
    ],
    accent: "#54E86B",
    text: "#F7F2F8",
    mute: "rgba(247, 242, 248, 0.42)",
    star: "rgba(255, 210, 255, 0.55)",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    bg: "#04121C",
    blobs: [
      { color: "rgba(12, 70, 92, 0.6)", x: 0.3, y: 0.2, r: 0.6 },
      { color: "rgba(8, 40, 80, 0.55)", x: 0.75, y: 0.35, r: 0.5 },
      { color: "rgba(20, 90, 110, 0.4)", x: 0.5, y: 0.75, r: 0.65 },
      { color: "rgba(6, 30, 50, 0.7)", x: 0.15, y: 0.85, r: 0.5 },
    ],
    accent: "#5EE0C8",
    text: "#F2FBFF",
    mute: "rgba(242, 251, 255, 0.42)",
    star: "rgba(180, 240, 255, 0.5)",
  },
  ember: {
    id: "ember",
    name: "Ember",
    bg: "#16080A",
    blobs: [
      { color: "rgba(120, 36, 24, 0.5)", x: 0.3, y: 0.22, r: 0.58 },
      { color: "rgba(80, 18, 30, 0.55)", x: 0.78, y: 0.18, r: 0.48 },
      { color: "rgba(90, 30, 18, 0.4)", x: 0.55, y: 0.7, r: 0.6 },
      { color: "rgba(40, 10, 12, 0.7)", x: 0.2, y: 0.88, r: 0.5 },
    ],
    accent: "#FFB25A",
    text: "#FFF6EE",
    mute: "rgba(255, 246, 238, 0.42)",
    star: "rgba(255, 210, 160, 0.5)",
  },
};

export const TEMPLATES: ReelContent[] = [
  {
    id: "apartheid",
    name: "Apartheid 1994",
    episode: "30",
    title: "The End of Apartheid",
    year: "1994",
    imageUrl: "/images/mandela-voting-1994.jpg",
    imageCaption: "Nelson Mandela voting, 1994",
    imageCredit: "Photo: Paul Weinberg, 1994 · CC BY-SA 3.0",
    bullets: [
      "Apartheid was South Africa’s legal system of racial segregation (1948–1994)",
      "Nelson Mandela spent 27 years in prison for anti-apartheid activism",
      "International boycotts and sanctions pressured the white minority government",
      "Mandela was released in 1990 and negotiated a peaceful transition",
      "First democratic elections held April 27, 1994 — Mandela became president",
      "At age 75, he chose reconciliation over revenge",
      "The Truth and Reconciliation Commission addressed past atrocities",
      "South Africa’s transition is studied as a model of peaceful revolution",
    ],
    hashtags: "#NelsonMandela #Apartheid #SouthAfrica #HistoryTok",
    handle: "@FactsOrWhacks",
    durationSec: 20,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "universe",
    name: "Observable universe",
    episode: "12",
    title: "The Observable Universe",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "The universe is about 13.8 billion years old, dating from the Big Bang",
      "The observable universe spans roughly 93 billion light-years",
      "It holds on the order of 2 trillion galaxies, each packed with stars",
      "There are more stars out there than grains of sand on Earth",
      "We live on one planet, on one arm, of one galaxy among billions",
    ],
    hashtags: "#Space #Universe #Astronomy #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 15,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "oceans",
    name: "Earth's oceans",
    episode: "18",
    title: "How Deep Earth's Oceans Go",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Water covers about 71% of Earth’s surface",
      "The average seafloor sits roughly 3.7 km down",
      "The Mariana Trench plunges about 11 km",
      "Less than 25% of the seafloor is mapped in high detail",
      "Most of Earth’s habitable space is ocean, not land",
    ],
    hashtags: "#Ocean #Earth #Science #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 15,
    theme: "ocean",
    reveal: "hold",
  },
  {
    id: "internet",
    name: "Internet in a day",
    episode: "7",
    title: "What the Internet Moves in a Day",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Roughly 361 billion emails are sent in a single day",
      "People run about 8.5 billion Google searches daily",
      "Hundreds of millions of hours of video are watched every day",
      "Billions of new images are uploaded across the web",
      "The day’s data traffic outweighs every book ever printed",
    ],
    hashtags: "#Internet #Tech #Data #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 15,
    theme: "cosmic",
    reveal: "hold",
  },
  {
    id: "body",
    name: "Human body",
    episode: "4",
    title: "The Strange Scale of a Human Body",
    year: "",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "You are about 30 trillion cells, plus at least as many microbes",
      "The heart pumps around 7,500 liters of blood a day",
      "Nerve signals can fire at up to 120 meters per second",
      "Uncoiled DNA in one body would stretch to the Sun",
      "The brain has about 86 billion neurons and uses ~20% of your energy",
    ],
    hashtags: "#Body #Biology #Science #FactsOrWhacks",
    handle: "@FactsOrWhacks",
    durationSec: 15,
    theme: "ember",
    reveal: "hold",
  },
];

export function cloneTemplate(template: ReelContent): ReelContent {
  return {
    ...template,
    bullets: [...template.bullets],
  };
}

export function blankReel(): ReelContent {
  return {
    id: "custom",
    name: "Custom",
    episode: "1",
    title: "Your Headline",
    year: "2026",
    imageUrl: "",
    imageCaption: "",
    imageCredit: "",
    bullets: [
      "Lead with one clear sentence people can read in a breath",
      "Follow with the turning point or the number that matters",
      "Keep each line to a single fact, not a paragraph",
      "End on why it still matters",
    ],
    hashtags: "#HistoryTok #FactsOrWhacks",
    handle: "@YourHandle",
    durationSec: 20,
    theme: "cosmic",
    reveal: "hold",
  };
}
